### ISSUE TITLE
Error due to missing virials on some configurations

### ISSUE THREAD

**Issue by jameskermode** [ACEsuit/mace#13]
Using the `stress_develop` with the following input script and the attached `train.xyz` and `test.xyz` (renamed to add `.txt` extensions) leads to an error.

[test.xyz.txt](https://github.com/ACEsuit/mace/files/9488752/test.xyz.txt)
[train.xyz.txt](https://github.com/ACEsuit/mace/files/9488753/train.xyz.txt)

```bash
python -i ../mace/scripts/run_train.py \
    --name="MACE_model" \
    --train_file="train.xyz" \
    --valid_fraction=0.05 \
    --test_file="test.xyz" \
    --config_type_weights='{"Default":1.0}' \
    --model="MACE" \
    --hidden_irreps='128x0e + 128x1o' \
    --r_max=5.0 \
    --batch_size=10 \
    --max_num_epochs=1500 \
    --swa \
    --start_swa=1200 \
    --ema \
    --ema_decay=0.99 \
    --amsgrad \
    --device=cuda \
    --forces_key=dft_force \
    --energy_key=dft_energy \
    --virials_key=dft_virial \
    --loss=virials
```

Traceback is as follows, with interactive debugging that it its `ref["virals"]` which is `None`.

```
2022-09-05 10:51:12.044 INFO: Started training
Traceback (most recent call last):
  File "../mace/scripts/run_train.py", line 405, in <module>
    main()
  File "../mace/scripts/run_train.py", line 346, in main
    tools.train(
  File "/gpfs/home/e/essswb/mace-venv/lib/python3.8/site-packages/mace/tools/train.py", line 69, in train
    _, opt_metrics = take_step(
  File "/gpfs/home/e/essswb/mace-venv/lib/python3.8/site-packages/mace/tools/train.py", line 206, in take_step
    loss = loss_fn(pred=output, ref=batch)
  File "/sulis/easybuild/software/PyTorch/1.9.0-fosscuda-2020b/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/gpfs/home/e/essswb/mace-venv/lib/python3.8/site-packages/mace/modules/loss.py", line 172, in forward
    + self.virials_weight * weighted_mean_squared_virials(ref, pred)
  File "/gpfs/home/e/essswb/mace-venv/lib/python3.8/site-packages/mace/modules/loss.py", line 41, in weighted_mean_squared_virials
    configs_weight * torch.square((ref["virials"] - pred["virials"]) / num_atoms)
  File "/sulis/easybuild/software/PyTorch/1.9.0-fosscuda-2020b/lib/python3.8/site-packages/torch/_tensor.py", line 544, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
TypeError: rsub() received an invalid combination of arguments - got (Tensor, NoneType), but expected one of:
 * (Tensor input, Tensor other, *, Number alpha)
 * (Tensor input, Number other, Number alpha)
```

**Comment by jameskermode** [comment]
That would work fine, thanks.  The typical idea is to include virials on small unit cells where they can be accurately converged with DFT but not for the larger cells.

**Comment by bernstei** [comment]
I was starting to test stress support, but I'm running into the same issue (no stresses for my isolated dimer configuration). Is there support for per-config-type per-property weights yet?

**Comment by ilyes319** [comment]
The PR #22 was merged so we can probably close that. @bernstei
