### ISSUE TITLE
Runtime error: don't know how to restore data loc of torch.storaget.UntypedStorage (tagges with gpu)

### ISSUE THREAD

**Issue by DGKang234** [ACEsuit/mace#146]
Hi,

**Describe the bug**
I have trained a model and used the model to produce a dimer curve. Both work is done in a single job.
After I trained the model. I tried to reuse the model to produce the same dimer curve by using the same python method.
However, it raises the runtime error:

Traceback (most recent call last):
  File "/home/uccatka/MACE/MACE_lib.py", line 256, in <module>
    mace.dimer_curve(args.model_path, args.device_type)
  File "/home/uccatka/MACE/MACE_lib.py", line 118, in dimer_curve
    calculator = MACECalculator(model_path=f"{model_path}.model", device=device_type)
  File "/lustre/home/uccatka/mace-venv/lib/python3.9/site-packages/mace/calculators/mace.py", line 33, in __init__
    self.model = torch.load(f=model_path, map_location=device)
  File "/lustre/home/uccatka/mace-venv/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/lustre/home/uccatka/mace-venv/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/lustre/home/uccatka/mace-venv/lib/python3.9/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/lustre/home/uccatka/mace-venv/lib/python3.9/site-packages/torch/serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/lustre/home/uccatka/mace-venv/lib/python3.9/site-packages/torch/serialization.py", line 1083, in restore_location
    return default_restore_location(storage, map_location)
  File "/lustre/home/uccatka/mace-venv/lib/python3.9/site-packages/torch/serialization.py", line 220, in default_restore_location
    raise RuntimeError("don't know how to restore data location of "
RuntimeError: don't know how to restore data location of torch.storage.UntypedStorage (tagged with gpu)

_line 118: calculator = MACECalculator(model_path=f"{model_path}.model", device=device_type)_

How should I resolve the error?

Thank you for your time.

**Comment by davkovacs** [comment]
Do you get the same error if you try setting device to cpu?

**Comment by DGKang234** [comment]
@davkovacs
The model is trained with gpu (I believe the gpu trained model cannot be loaded using cpu?)

I attempted with cpu this time (loading gpu trained model).
(mace-venv) [uccatka@login02 FIT_old]$ python /home/uccatka/MACE/MACE_lib.py --model_path="n3_dft_001_all_6.0" --device_type="cpu" --skip_training --dimer
Traceback (most recent call last):
  File "/home/uccatka/MACE/MACE_lib.py", line 417, in <module>
    mace.dimer_curve(args.model_path, args.device_type)
  File "/home/uccatka/MACE/MACE_lib.py", line 118, in dimer_curve
    calculator = MACECalculator(model_path=f"{model_path}.model", device=device_type)
  File "/lustre/home/uccatka/mace-venv/lib/python3.9/site-packages/mace/calculators/mace.py", line 33, in __init__
    self.model = torch.load(f=model_path, map_location=device)
  File "/lustre/home/uccatka/mace-venv/lib/python3.9/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/lustre/home/uccatka/mace-venv/lib/python3.9/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/lustre/home/uccatka/mace-venv/lib/python3.9/site-packages/e3nn/util/codegen/_mixin.py", line 109, in __setstate__
    smod = torch.jit.load(buffer)
  File "/lustre/home/uccatka/mace-venv/lib/python3.9/site-packages/torch/jit/_serialization.py", line 164, in load
    cpp_module = torch._C.import_ir_module_from_buffer(
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by DGKang234** [comment]
I got a comment from rc support team:

Would this be helpful to fix the bug?

# Saving Models #
A common way to save a model is to serialize the internal state dictionary (containing the model parameters).
```
torch.save(model.state_dict(), "model.pth") 
print("Saved PyTorch Model State to model.pth")
```
# Loading Models # 
The process for loading a model includes re-creating the model structure and loading
the state dictionary into it. 
```
model = NeuralNetwork() 
model.load_state_dict(torch.load("model.pth"))
```
