### ISSUE TITLE
Exporting models for use on multiple platforms

### ISSUE THREAD

**Issue by kkly1995** [ACEsuit/mace#153]
I have a model that I would like to be able to use on multiple machines, and share with collaborators. This model was trained using a GPU via CUDA, and I also regularly use it via the ASE calculator, also on the GPU. However, I would like to be able to use the calculator on my own machine for testing, and my machine does not have CUDA. I have also tested it with another non-CUDA machine and I get the same error. I've pasted the full traceback message at the bottom.

**Describe the bug**
When training with CUDA, it seems like the resulting model can only be loaded into an ASE calculator with `device='cuda'`.

**To Reproduce**
[my_model.zip](https://github.com/ACEsuit/mace/files/12579499/my_model.zip)
Model attached above. Loading the model with `device='cuda', default_dtype='float32'` works, but changing `cuda` to e.g. `cpu` leads to the error below.

**Machines**
Trained on NCSA's [HAL](https://wiki.ncsa.illinois.edu/display/ISL20/HAL+cluster), also successfully loaded calculator on NERSC's [Perlmutter](https://docs.nersc.gov/systems/perlmutter/), which has CUDA GPUs.
Unsuccessful on my personal Macbook (M2 Pro) and an office workstation (Intel Xeon E5-2620)

**Error message**
```
In [1]: from mace.calculators import MACECalculator

In [2]: calc = MACECalculator('hydrogen.model', device='cpu', default_dtype='float32')
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-2-feb0b948df05> in <module>
----> 1 calc = MACECalculator('hydrogen.model', device='cpu', default_dtype='float32')

~/anaconda3/lib/python3.8/site-packages/mace/calculators/mace.py in __init__(self, model_path, device, energy_units_to_eV, length_units_to_A, default_dtype, **kwargs)
     31         self.results = {}
     32
---> 33         self.model = torch.load(f=model_path, map_location=device)
     34         self.r_max = float(self.model.r_max)
     35         self.device = torch_tools.init_device(device)

~/anaconda3/lib/python3.8/site-packages/torch/serialization.py in load(f, map_location, pickle_module, weights_only, **pickle_load_args)
    807                     except RuntimeError as e:
    808                         raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
--> 809                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    810         if weights_only:
    811             try:

~/anaconda3/lib/python3.8/site-packages/torch/serialization.py in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
   1170     unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
   1171     unpickler.persistent_load = persistent_load
-> 1172     result = unpickler.load()
   1173
   1174     torch._utils._validate_loaded_sparse_tensors()

~/anaconda3/lib/python3.8/site-packages/e3nn/util/codegen/_mixin.py in __setstate__(self, d)
    107                 # Load the TorchScript IR buffer
    108                 buffer = io.BytesIO(buffer)
--> 109                 smod = torch.jit.load(buffer)
    110                 assert isinstance(smod, torch.jit.ScriptModule)
    111                 # Add the ScriptModule as a submodule

~/anaconda3/lib/python3.8/site-packages/torch/jit/_serialization.py in load(f, map_location, _extra_files, _restore_shapes)
    162         cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files, _restore_shapes)  # type: ignore[call-arg]
    163     else:
--> 164         cpp_module = torch._C.import_ir_module_from_buffer(
    165             cu, f.read(), map_location, _extra_files, _restore_shapes
    166         )  # type: ignore[call-arg]

NotImplementedError: Could not run 'aten::empty_strided' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::empty_strided' is only available for these backends: [CPU, Meta, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].

CPU: registered at aten/src/ATen/RegisterCPU.cpp:31034 [kernel]
Meta: registered at aten/src/ATen/RegisterMeta.cpp:26824 [kernel]
QuantizedCPU: registered at aten/src/ATen/RegisterQuantizedCPU.cpp:929 [kernel]
BackendSelect: registered at aten/src/ATen/RegisterBackendSelect.cpp:726 [kernel]
Python: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:144 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at ../aten/src/ATen/functorch/DynamicLayer.cpp:491 [backend fallback]
Functionalize: registered at ../aten/src/ATen/FunctionalizeFallbackKernel.cpp:280 [backend fallback]
Named: registered at ../aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: fallthrough registered at ../aten/src/ATen/ConjugateFallback.cpp:21 [kernel]
Negative: fallthrough registered at ../aten/src/ATen/native/NegateFallback.cpp:23 [kernel]
ZeroTensor: fallthrough registered at ../aten/src/ATen/ZeroTensorFallback.cpp:90 [kernel]
ADInplaceOrView: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:63 [backend fallback]
AutogradOther: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradCPU: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradCUDA: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradHIP: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradXLA: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradMPS: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradIPU: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradXPU: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradHPU: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradVE: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradLazy: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradMeta: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradMTIA: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradPrivateUse1: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradPrivateUse2: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradPrivateUse3: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
AutogradNestedTensor: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:17472 [autograd kernel]
Tracer: registered at ../torch/csrc/autograd/generated/TraceTy
pe_2.cpp:16726 [kernel]
AutocastCPU: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:487 [backend fallback]
AutocastCUDA: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:354 [backend fallback]
FuncTorchBatched: registered at ../aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:815 [backend fallback]
FuncTorchVmapMode: fallthrough registered at ../aten/src/ATen/functorch/VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at ../aten/src/ATen/LegacyBatchingRegistrations.cpp:1073 [backend fallback]
VmapMode: fallthrough registered at ../aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at ../aten/src/ATen/functorch/TensorWrapper.cpp:210 [backend fallback]
PythonTLSSnapshot: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:152 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ../aten/src/ATen/functorch/DynamicLayer.cpp:487 [backend fallback]
PythonDispatcher: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:148 [backend fallback]
```

**Comment by ilyes319** [comment]
Did you make sure to enable the `--save_cpu` flag during your training?
If not could you try to run the following script:
```
import torch
model = torch.load("path", device="cuda")
model = model.cpu()
model = torch.save("path", model)
```

**Comment by kkly1995** [comment]
I did not set `save_cpu` during training. I also ran into the following error which occurs in the final line of your suggestion:
```
$ python save_cpu.py
/home/ly1/.local/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/serialization.py", line 591, in _save
    zip_file.write_record('data.pkl', data_value, len(data_value))
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ScaleShiftMACE' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/serialization.py", line 380, in save
    return
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/serialization.py", line 259, in __exit__
    self.file_like.write_end_of_file()
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ScaleShiftMACE' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ly1/H/metallic/mace/subtracted/force_weight/save_cpu.py", line 5, in <module>
    model = torch.save('cpu_hydrogen.model', model)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/serialization.py", line 381, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/serialization.py", line 225, in __exit__
    self.file_like.flush()
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ScaleShiftMACE' object has no attribute 'flush'
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  AttributeError: 'ScaleShiftMACE' object has no attribute 'write'

At:
  /home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py(1207): __getattr__

Aborted (core dumped)
```
using the following script
```
$ cat save_cpu.py
import torch

model = torch.load('hydrogen.model') # device does not appear to be a kwarg
model = model.cpu()
model = torch.save('cpu_hydrogen.model', model)
```

**Comment by ilyes319** [comment]
Sorry you need to change the last line to `model = torch.save(model, 'cpu_hydrogen.model')`

**Comment by kkly1995** [comment]
That worked, thank you! So I need to have two different files, one for the GPU version, and another for the CPU version?

**Comment by gabor1** [comment]
Why can't we have that option as default? every other issue is about that.

**Comment by kkly1995** [comment]
If I try to load the CPU model that I just got using Ilyes' suggestion with `device='cuda'`, I get the following error:
```
$ python load_cpu_model.py
/home/ly1/.local/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/home/ly1/H/metallic/mace/subtracted/force_weight/load_cpu_model.py", line 8, in <module>
    energy = sample.get_potential_energy()
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/ase/atoms.py", line 731, in get_potential_energy
    energy = self._calc.get_potential_energy(self)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/ase/calculators/calculator.py", line 709, in get_potential_energy
    energy = self.get_property('energy', atoms)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/ase/calculators/calculator.py", line 737, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/mace/calculators/mace.py", line 71, in calculate
    out = self.model(batch.to_dict(), compute_stress=True)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/mace/modules/models.py", line 315, in forward
    node_feats, sc = interaction(
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/mace/modules/blocks.py", line 600, in forward
    mji = self.conv_tp(
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/e3nn/o3/_tensor_product/_tensor_product.py", line 529, in forward
    return self._compiled_main_left_right(x, y, real_weight)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch/fx/graph_module/___torch_mangle_11.py", line 97, in forward
    _w3j_1_2_1 = self._w3j_1_2_1
    mul_1 = torch.mul(_w3j_1_2_1, 1.7320508075688772)
    tensordot = _0(einsum_11, mul_1, ([4, 3], [1, 0]), None, )
                ~~ <--- HERE
    einsum_12 = torch.einsum("dbca,dbc->dba", [tensordot, reshape_21])
    reshape_22 = torch.reshape(einsum_12, [getitem_4, 192])
  File "code/__torch__/torch/functional/___torch_mangle_0.py", line 9, in tensordot
  dims_a, dims_b, = dims1
  if torch.__is__(out, None):
    _1 = torch.tensordot(a, b, dims_a, dims_b)
         ~~~~~~~~~~~~~~~ <--- HERE
    _0 = _1
  else:

Traceback of TorchScript, original code (most recent call last):
  File "<eval_with_key>.127", line 75, in forward
    _w3j_1_2_1 = self._w3j_1_2_1
    mul_1 = _w3j_1_2_1 * 1.7320508075688772;  _w3j_1_2_1 = None
    tensordot = torch.functional.tensordot(einsum_11, mul_1, ([4, 3], [1, 0]), out = None);  mul_1 = None
                ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    einsum_12 = torch.functional.einsum('dbca,dbc->dba', tensordot, reshape_21);  tensordot = reshape_21 = None
    reshape_22 = einsum_12.reshape(getitem_4, 192);  einsum_12 = None
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/functional.py", line 1064, in tensordot

    if out is None:
        return _VF.tensordot(a, b, dims_a, dims_b)  # type: ignore[attr-defined]
               ~~~~~~~~~~~~~ <--- HERE
    else:
        return _VF.tensordot(a, b, dims_a, dims_b, out=out)  # type: ignore[attr-defined]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_mm)
```

Here is the script that was executed
```
$ cat load_cpu_model.py
from mace.calculators import MACECalculator
from ase.io import read

calc = MACECalculator('cpu_hydrogen.model', device='cuda', default_dtype='float32')
sample = read('mcase/small_melting/500/samples.xyz')

sample.calc = calc
energy = sample.get_potential_energy()
```
The error only appears at the last line when the calculator is actually called on the Atoms object, there is no error when the calculator is initially be read from file, which differs from the error in my initial post. There is also no error if I switch to `device='cpu'`, and the outcome of the calculator is correct. Is the file produced by setting `--save_cpu` the same?

**Comment by bernstei** [comment]
> the conversion CPU -> GPU is safe either

I'm going to assume you meant "isn't", and if so, that's crazy.

Does the GPU fail if you try to load onto a (sufficiently) different GPU?
