### ISSUE TITLE
multi-GPU doesn't seem to really accelerate fitting. 

### ISSUE THREAD

**Issue by jungsdao** [ACEsuit/mace#156]
Hello, 
I have posted some issue related to multi-GPU, but I realized that I was not using the most recent commit of the multi-GPU branch and it was resolved after updating the code. 
After following some steps on multi-GPU on the documentation, I have compared the fitting speed of with/without multi-GPU.  
However, even after preprocessing the data, the speed of fitting is not faster than without multi-GPU.
I'm suspecting that this fitting job did not invoked multi-GPU fitting because I couldn't see this output in the logfiile `Multi-GPUs training on 2 GPUs`.
So it seems that multi-GPU fitting is not working as intended. 
Could you advice me how can I carry out multi-GPU fitting properly? 
Following is my fitting command and log file is attached. 
Many thanks in advance!

```
python  ~/Softwares/mace/scripts/run_train.py \
    --name="MACE_model" \
    --train_file='./processed_data/train.h5' \
    --valid_file='./processed_data/valid.h5' \
    --statistics_file="./processed_data/statistics.json" \
    --model="MACE" \
    --distributed \
	--config_type_weights='{"Default":1.0}' \
    --E0s='average' \
	--energy_key="free_energy" \
    --num_interactions=2 \
    --num_channels=64 \
    --max_L=1 \
    --correlation=3 \
    --r_max=6.0 \
    --forces_weight=1000 \
    --energy_weight=1000 \
    --batch_size=16 \
    --valid_batch_size=16 \
    --max_num_epochs=100 \
    --scheduler_patience=15 \
    --patience=30 \
    --eval_interval=4 \
    --ema \
    --swa \
    --start_swa=70 \
    --error_table='PerAtomMAE' \
    --device=cuda \
    --restart_latest \
    --save_cpu \
```
[MACE_model_run-123.log](https://github.com/ACEsuit/mace/files/12610788/MACE_model_run-123.log)

**Comment by davkovacs** [comment]
Could you check the utilisation with something like `nvitop`  to see if it was using both GPU-s? 
Also, were you using slurm to launch the job / is the node on a slurm cluster?

**Comment by jungsdao** [comment]
Thank you for prompt reply!
I'm using slurm to launch the job. (I submitted to 2 GPU on a shared node.)
I have no idea how to check utilization with `nvitop`. Could you provide me snippet of an example?

**Comment by davkovacs** [comment]
I think you just pip install `nvitop` and than ssh to the node where your training is running and do `nvitop` in the terminal. It will do something similar to `top` for seeing CPU utilisation, but you will see real time GPU utilisation. Alternatively you can also do `nvidia-smi` on the node which should also print utilisation of all GPU-s.

**Comment by jungsdao** [comment]
I have added following environment variable setting to submission script. 
```
ms_addr=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
export MASTER_ADDR=$ms_addr
export MASTER_PORT=12321
export WORLD_SIZE=$(($SLURM_NNODES * $SLURM_NTASKS_PER_NODE))
```

and I have tried `nvidia-smi` couple of minutes and I've got following outputs
```
timestamp, name, pci.bus_id, driver_version, pstate, pcie.link.gen.max, pcie.link.gen.current, temperature.gpu, utilization.gpu [%], utilization.memory [%], memory.total [MiB], memory.free [MiB], memory.used [MiB]
2023/09/15 17:55:55.294, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 29, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:55:55.298, NVIDIA A100-SXM4-40GB, 00000000:4B:00.0, 535.86.10, P0, 4, 4, 28, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:55:55.302, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 27, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:55:55.306, NVIDIA A100-SXM4-40GB, 00000000:E3:00.0, 535.86.10, P0, 4, 4, 28, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:05.311, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 29, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:05.316, NVIDIA A100-SXM4-40GB, 00000000:4B:00.0, 535.86.10, P0, 4, 4, 28, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:05.319, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 27, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:05.321, NVIDIA A100-SXM4-40GB, 00000000:E3:00.0, 535.86.10, P0, 4, 4, 28, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:15.324, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 29, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:15.330, NVIDIA A100-SXM4-40GB, 00000000:4B:00.0, 535.86.10, P0, 4, 4, 28, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:15.333, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 27, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:15.336, NVIDIA A100-SXM4-40GB, 00000000:E3:00.0, 535.86.10, P0, 4, 4, 28, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:25.340, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 29, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:25.346, NVIDIA A100-SXM4-40GB, 00000000:4B:00.0, 535.86.10, P0, 4, 4, 28, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:25.348, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 27, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:25.352, NVIDIA A100-SXM4-40GB, 00000000:E3:00.0, 535.86.10, P0, 4, 4, 28, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:35.355, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 29, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:35.361, NVIDIA A100-SXM4-40GB, 00000000:4B:00.0, 535.86.10, P0, 4, 4, 28, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:35.363, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 27, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:35.366, NVIDIA A100-SXM4-40GB, 00000000:E3:00.0, 535.86.10, P0, 4, 4, 28, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:45.369, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 29, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:45.374, NVIDIA A100-SXM4-40GB, 00000000:4B:00.0, 535.86.10, P0, 4, 4, 28, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:45.376, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 27, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:45.379, NVIDIA A100-SXM4-40GB, 00000000:E3:00.0, 535.86.10, P0, 4, 4, 28, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:55.382, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 29, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:55.389, NVIDIA A100-SXM4-40GB, 00000000:4B:00.0, 535.86.10, P0, 4, 4, 27, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:55.391, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 27, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:56:55.399, NVIDIA A100-SXM4-40GB, 00000000:E3:00.0, 535.86.10, P0, 4, 4, 28, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:57:05.403, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 29, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
2023/09/15 17:57:05.409, NVIDIA A100-SXM4-40GB, 00000000:4B:00.0, 535.86.10, P0, 4, 4, 27, 0 %, 0 %, 40960 MiB, 40334 MiB, 4 MiB
```
I guess since there're 4 outputs per each identical timestamp, this means that 4 GPUs are in operation.
However, in this case, I've got different sort of error as following 
Could you advice me for possible solutions?
Thank you!
```
/u/hjung/conda-envs/mace_env/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /raven/u/hjung/conda-envs/mace_env/lib/python3.9/site-packages/torchvision/image.so: undefined symbol:
 _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/u/hjung/Softwares/mace/scripts/run_train.py", line 661, in <module>
    main()
  File "/u/hjung/Softwares/mace/scripts/run_train.py", line 52, in main
    torch.distributed.init_process_group(backend='nccl')
  File "/u/hjung/conda-envs/mace_env/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 932, in init_process_group
    _store_based_barrier(rank, store, timeout)
  File "/u/hjung/conda-envs/mace_env/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 469, in _store_based_barrier
    raise RuntimeError(
RuntimeError: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=4, worker_count=1, timeout=0:30:00)
```

**Comment by jungsdao** [comment]
When I submit job without setting above environment variable (`MASTER_ADDR`, `MASTER_PORT`,  `WORLD_SIZE`), it runs without timeout error. 
But when I get output from `nvidia-smi`, I can see only one of two GPUs is utilized. (In this case I submitted to used two GPUs)

```
2023/09/15 22:33:05.672, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 32, 0 %, 0 %, 40960 MiB, 11028 MiB, 29310 MiB
2023/09/15 22:33:05.674, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:33:15.678, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 30, 0 %, 0 %, 40960 MiB, 11028 MiB, 29310 MiB
2023/09/15 22:33:15.679, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:33:25.683, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 35, 52 %, 36 %, 40960 MiB, 11028 MiB, 29310 MiB
2023/09/15 22:33:25.687, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:33:35.690, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 32, 65 %, 50 %, 40960 MiB, 11028 MiB, 29310 MiB
2023/09/15 22:33:35.692, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:33:45.695, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 33, 28 %, 20 %, 40960 MiB, 6804 MiB, 33534 MiB
2023/09/15 22:33:45.697, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:33:55.701, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 33, 64 %, 50 %, 40960 MiB, 2256 MiB, 38082 MiB
2023/09/15 22:33:55.703, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:34:05.706, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 34, 70 %, 57 %, 40960 MiB, 2256 MiB, 38082 MiB
2023/09/15 22:34:05.709, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:34:15.712, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 37, 41 %, 27 %, 40960 MiB, 2256 MiB, 38082 MiB
2023/09/15 22:34:15.716, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:34:25.720, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 34, 45 %, 35 %, 40960 MiB, 2254 MiB, 38084 MiB
2023/09/15 22:34:25.721, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:34:35.725, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 37, 37 %, 24 %, 40960 MiB, 2254 MiB, 38084 MiB
2023/09/15 22:34:35.728, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:34:45.731, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 35, 7 %, 6 %, 40960 MiB, 2254 MiB, 38084 MiB
2023/09/15 22:34:45.735, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:34:55.738, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 34, 17 %, 12 %, 40960 MiB, 2254 MiB, 38084 MiB
2023/09/15 22:34:55.741, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:35:05.744, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 34, 55 %, 42 %, 40960 MiB, 2254 MiB, 38084 MiB
2023/09/15 22:35:05.747, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:35:15.751, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 38, 91 %, 68 %, 40960 MiB, 2254 MiB, 38084 MiB
2023/09/15 22:35:15.756, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:35:25.760, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 36, 95 %, 77 %, 40960 MiB, 2254 MiB, 38084 MiB
2023/09/15 22:35:25.763, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:35:35.766, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 38, 95 %, 69 %, 40960 MiB, 2254 MiB, 38084 MiB
2023/09/15 22:35:35.771, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:35:45.774, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 37, 18 %, 11 %, 40960 MiB, 2254 MiB, 38084 MiB
2023/09/15 22:35:45.777, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:35:55.780, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 34, 69 %, 52 %, 40960 MiB, 2254 MiB, 38084 MiB
2023/09/15 22:35:55.782, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:36:05.785, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 37, 98 %, 75 %, 40960 MiB, 2254 MiB, 38084 MiB
2023/09/15 22:36:05.824, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:36:15.827, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 34, 3 %, 2 %, 40960 MiB, 2254 MiB, 38084 MiB
2023/09/15 22:36:15.829, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:36:25.832, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 34, 49 %, 36 %, 40960 MiB, 2254 MiB, 38084 MiB
2023/09/15 22:36:25.835, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
2023/09/15 22:36:35.838, NVIDIA A100-SXM4-40GB, 00000000:31:00.0, 535.86.10, P0, 4, 4, 35, 64 %, 48 %, 40960 MiB, 16198 MiB, 24140 MiB
2023/09/15 22:36:35.840, NVIDIA A100-SXM4-40GB, 00000000:CA:00.0, 535.86.10, P0, 4, 4, 26, 0 %, 0 %, 40960 MiB, 40330 MiB, 8 MiB
```

**Comment by jungsdao** [comment]
This problem has been resolved by calling distributed pytorch module in the cluster. 
Now it works as expected, Thank you!

**Comment by davkovacs** [comment]
Great!
