### ISSUE TITLE
Checkpoint not saving SWA model and crashing

### ISSUE THREAD

**Issue by zakmachachi** [ACEsuit/mace#176]
**Describe the bug**
I have been training models using the same version of the develop branch for a couple of months now and up until this week everything was working fine. Now I get the following trace:

```
023-09-28 00:28:43.409 INFO: Training complete
2023-09-28 00:28:43.409 INFO: Computing metrics for training, validation, and test sets
2023-09-28 00:28:43.409 INFO: Loading checkpoint: checkpoints/MACE_model_run-123_epoch-500.pt
2023-09-28 00:28:43.422 INFO: Loaded model from epoch 500
2023-09-28 00:28:44.704 INFO: Evaluating train ...
2023-09-28 00:28:56.208 INFO: Evaluating valid ...
2023-09-28 00:28:57.252 INFO: Evaluating 0.40-0.75 ...
2023-09-28 00:28:57.407 INFO: Evaluating 0.10-0.75 ...
2023-09-28 00:28:57.483 INFO: Evaluating 0.30-0.50 ...
2023-09-28 00:28:57.579 INFO: Evaluating 0.20-0.00 ...
2023-09-28 00:28:57.663 INFO: Evaluating 0.50-0.00 ...
2023-09-28 00:28:57.752 INFO: Evaluating 0.10-0.50 ...
2023-09-28 00:28:57.825 INFO: Evaluating 0.10-0.25 ...
2023-09-28 00:28:57.913 INFO: Evaluating 0.50-0.50 ...
2023-09-28 00:28:58.044 INFO: Evaluating 0.20-0.25 ...
2023-09-28 00:28:58.126 INFO: Evaluating 0.10-0.00 ...
2023-09-28 00:28:58.199 INFO: Evaluating 0.20-0.75 ...
2023-09-28 00:28:58.281 INFO: Evaluating 0.50-1.00 ...
2023-09-28 00:28:58.396 INFO: Evaluating 0.30-0.25 ...
2023-09-28 00:28:58.533 INFO: Evaluating 0.30-0.75 ...
2023-09-28 00:28:58.666 INFO: Evaluating 0.20-0.50 ...
2023-09-28 00:28:58.746 INFO: Evaluating 0.50-0.25 ...
2023-09-28 00:28:58.835 INFO: Evaluating 0.30-0.00 ...
2023-09-28 00:28:58.916 INFO: Evaluating 0.40-0.00 ...
2023-09-28 00:28:59.013 INFO: Evaluating 0.40-1.00 ...
2023-09-28 00:28:59.164 INFO: Evaluating 0.20-1.00 ...
2023-09-28 00:28:59.244 INFO: Evaluating 0.40-0.50 ...
2023-09-28 00:28:59.333 INFO: Evaluating 0.10-1.00 ...
2023-09-28 00:28:59.411 INFO: Evaluating 0.40-0.25 ...
2023-09-28 00:28:59.526 INFO: Evaluating 0.30-1.00 ...
2023-09-28 00:28:59.632 INFO: Evaluating 0.50-0.75 ...
2023-09-28 00:28:59.755 INFO: 
+-------------+---------------------+------------------+-------------------+---------------------------------------+
| config_type | RMSE E / meV / atom | RMSE F / meV / A | relative F RMSE % | RMSE Stress (Virials) / meV / A (A^3) |
+-------------+---------------------+------------------+-------------------+---------------------------------------+
|    train    |         15.3        |      307.2       |        8.78       |                  8.6                  |
|    valid    |         17.0        |      916.7       |       24.53       |                  8.2                  |
|  0.40-0.75  |         6.4         |      134.6       |        8.91       |                  7.5                  |
|  0.10-0.75  |         8.0         |      102.3       |        6.54       |                  2.4                  |
|  0.30-0.50  |         7.7         |      152.2       |        8.17       |                  6.7                  |
|  0.20-0.00  |         5.8         |      126.1       |        8.69       |                  6.4                  |
|  0.50-0.00  |         13.6        |      191.6       |       12.29       |                  13.9                 |
|  0.10-0.50  |         7.6         |       95.9       |        5.25       |                  2.5                  |
|  0.10-0.25  |         7.6         |      116.0       |        6.35       |                  3.6                  |
|  0.50-0.50  |         7.1         |      233.3       |       13.70       |                  9.7                  |
|  0.20-0.25  |         7.8         |      131.4       |        7.11       |                  6.2                  |
|  0.10-0.00  |         7.2         |      115.0       |        5.99       |                  4.8                  |
|  0.20-0.75  |         7.0         |      114.0       |        6.52       |                  4.4                  |
|  0.50-1.00  |         5.3         |      157.5       |        9.28       |                  6.2                  |
|  0.30-0.25  |         8.0         |      138.3       |        8.11       |                  8.1                  |
|  0.30-0.75  |         5.5         |      129.3       |        8.12       |                  6.0                  |
|  0.20-0.50  |         6.0         |      126.5       |        7.09       |                  4.2                  |
|  0.50-0.25  |         8.7         |      212.6       |       10.99       |                  11.1                 |
|  0.30-0.00  |         10.4        |      163.8       |        9.25       |                  12.2                 |
|  0.40-0.00  |         12.8        |      144.3       |        9.95       |                  11.7                 |
|  0.40-1.00  |         5.8         |      134.9       |        8.89       |                  5.8                  |
|  0.20-1.00  |         8.4         |      118.4       |        6.32       |                  2.8                  |
|  0.40-0.50  |         5.1         |      142.1       |        9.77       |                  7.3                  |
|  0.10-1.00  |         8.7         |      102.6       |        6.26       |                  2.6                  |
|  0.40-0.25  |         56.8        |      3747.1      |       27.01       |                  15.6                 |
|  0.30-1.00  |         4.6         |      128.0       |        7.39       |                  4.2                  |
|  0.50-0.75  |         12.0        |      425.8       |       26.00       |                  11.8                 |
+-------------+---------------------+------------------+-------------------+---------------------------------------+
2023-09-28 00:28:59.755 INFO: Saving model to checkpoints/MACE_model_run-123.model
Traceback (most recent call last):
  File "/u/vld/sedm6197/software/mace/scripts/run_train.py", line 562, in <module>
    main()
  File "/u/vld/sedm6197/software/mace/scripts/run_train.py", line 519, in main
    epoch = checkpoint_handler.load_latest(
  File "/u/vld/sedm6197/miniconda3/envs/mace_env/lib/python3.9/site-packages/mace/tools/checkpoint.py", line 205, in load_latest
    result = self.io.load_latest(swa=swa, device=device)
  File "/u/vld/sedm6197/miniconda3/envs/mace_env/lib/python3.9/site-packages/mace/tools/checkpoint.py", line 166, in load_latest
    path = self._get_latest_checkpoint_path(swa=swa)
  File "/u/vld/sedm6197/miniconda3/envs/mace_env/lib/python3.9/site-packages/mace/tools/checkpoint.py", line 140, in _get_latest_checkpoint_path
    latest_checkpoint_info = max(
ValueError: max() arg is an empty sequence
```
As a result I do not get an SWA model at the end. The SWA switch happens at 500 epochs, but that 500th epoch turns out to have the lowest loss duing the SWA regime. If I restart the training then I get an SWA model. Perhaps this is just an edge case but still interesting to flag! I've trained on two seperate machines using the same database and get the same error, where the 500th model during the SWA switch had the smallest loss.

**To Reproduce**
```
#!/bin/bash

gpu_id=1
CUDA_VISIBLE_DEVICES="$gpu_id" python /u/vld/sedm6197/software/mace/scripts/run_train.py \
    --name="MACE_model" \
    --train_file="structures/iter-7-train.xyz" \
    --valid_fraction=0.10 \
    --test_file="structures/iter-7-test.xyz" \
    --config_type_weights='{"Default":1.0}' \
    --model="MACE" \
    --hidden_irreps='128x0e' \
    --loss='huber' \
    --r_max=3.7 \
    --batch_size=25 \
    --max_num_epochs=1200 \
    --swa \
    --default_dtype='float32' \
    --energy_key='QM_energy' \
    --forces_key='QM_forces' \
    --stress_key=None \
    --start_swa=500 \
    --ema \
    --ema_decay=0.99 \
    --amsgrad \
    --restart_latest \
    --device=cuda \
    --seed=123 \
```

**Expected behavior**
Two models to be yielded at the end of training, one model.model file and one model_swa.model file

**Desktop (please complete the following information):**
 - OS: Linux
 - Mace version 
```
 (mace_env) (base) [sedm6197@vld-gpu01 mace]$ git log -n 1
commit 55f741138d0acd85514682ea4df40afde02f212d (HEAD -> develop)
Author: Ilyes Batatia <48651863+ilyes319@users.noreply.github.com>
Date:   Fri Jul 21 11:10:36 2023 +0100

    fix calculator
```
LibTorch version
```
(mace_env) (base) [sedm6197@vld-gpu01 mace]$ python
Python 3.9.17 (main, Jul  5 2023, 20:41:20) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
2.0.1+cu118
```

**Comment by ilyes319** [comment]
Thank you for reporting that! It does look like a weird edge case.

**Comment by ilyes319** [comment]
This is the expected behavior as you are loading the 500 epoch but it has created no swa epoch yet (>500). You would just need to train for a bit longer. I have pushed a better error string to explain that.
