### ISSUE TITLE
Restart training error

### ISSUE THREAD

**Issue by bapatist** [ACEsuit/mace#180]
Hi all, while using the `restart_latest`, After loading of checkpoint and defining ScaleShiftMACE, I run into the following error with training 
```
Traceback (most recent call last):
  File "/u/nbapat/software/mace/scripts/run_train.py", line 562, in <module>
    main()
  File "/u/nbapat/software/mace/scripts/run_train.py", line 488, in main
    tools.train(
  File "/u/nbapat/conda-envs/mase/lib/python3.9/site-packages/mace/tools/train.py", line 92, in train
    _, opt_metrics = take_step(
  File "/u/nbapat/conda-envs/mase/lib/python3.9/site-packages/mace/tools/train.py", line 253, in take_step
    optimizer.step()
  File "/u/nbapat/conda-envs/mase/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/u/nbapat/conda-envs/mase/lib/python3.9/site-packages/torch/optim/optimizer.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "/u/nbapat/conda-envs/mase/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/u/nbapat/conda-envs/mase/lib/python3.9/site-packages/torch/optim/adam.py", line 157, in step
    adam(params_with_grad,
  File "/u/nbapat/conda-envs/mase/lib/python3.9/site-packages/torch/optim/adam.py", line 213, in adam
    func(params,
  File "/u/nbapat/conda-envs/mase/lib/python3.9/site-packages/torch/optim/adam.py", line 255, in _single_tensor_adam
    assert not step_t.is_cuda, "If capturable=False, state_steps should not be CUDA tensors."
AssertionError: If capturable=False, state_steps should not be CUDA tensors.
```
Fitting command:
```
#!/bin/bash -l
# Standard output and error:
#SBATCH -o ./job.out.%j
#SBATCH -e ./job.err.%j
# Initial working directory:
#SBATCH -D ./
# Job name
#SBATCH -J refit 
#
#SBATCH --ntasks=1
#SBATCH --constraint="gpu"
#SBATCH --gres=gpu:a100:1
#SBATCH --cpus-per-task=18
#SBATCH --mem=125000
#
#SBATCH --time=10:00:00

module purge
module load cuda/11.6
conda activate mase 
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}

## batch size computed by max_num_epochs*numconfigs/200,000

python /u/nbapat/software/mace/scripts/run_train.py \
    --name="MACE_model" \
    --train_file="train_with_test.xyz" \
    --valid_fraction=0.05 \
    --test_file="test_all_ITER4.xyz" \
    --config_type_weights='{"Default":1.0}' \
    --model="MACE" \
    --hidden_irreps='128x0e + 128x1o' \
    --batch_size=6 \
    --r_max=4.5 \
    --max_num_epochs=2000 \
    --swa \
    --start_swa=1750 \
    --ema \
    --ema_decay=0.99 \
    --amsgrad \
    --restart_latest \
    --device=cuda \
    --energy_key=DFT_energy \
    --forces_key=DFT_forces
```

**Comment by bapatist** [comment]
Any ideas for what could be the source of the error? I'm still stuck with the restart-fits. Regular fits work fine.

**Comment by bapatist** [comment]
Here's the log:
```
2023-10-09 17:49:47.240 INFO: MACE version: 0.2.0
2023-10-09 17:49:47.240 INFO: Configuration: Namespace(name='MACE_model', seed=123, log_dir='logs', model_dir='.', checkpoints_dir='checkpoints', results_dir='results', downloads_dir='downloads', device='cuda', default_dtype='float64', log_level='INFO', error_table='PerAtomRMSE', model='MACE', r_max=4.5, num_radial_basis=8, num_cutoff_basis=5, interaction='RealAgnosticResidualInteractionBlock', interaction_first='RealAgnosticResidualInteractionBlock', max_ell=3, correlation=3, num_interactions=2, MLP_irreps='16x0e', hidden_irreps='128x0e + 128x1o', num_channels=None, max_L=None, gate='silu', scaling='rms_forces_scaling', avg_num_neighbors=1, compute_avg_num_neighbors=True, compute_stress=False, compute_forces=True, train_file='/tmp/_MACE_fitting_configs.23_ymmq3.xyz', valid_file=None, valid_fraction=0.05, test_file=None, E0s=None, energy_key='DFT_energy', forces_key='DFT_forces', virials_key='virials', stress_key='stress', dipole_key='dipole', charges_key='charges', loss='weighted', forces_weight=10.0, swa_forces_weight=1.0, energy_weight=1.0, swa_energy_weight=1000.0, virials_weight=1.0, swa_virials_weight=10.0, stress_weight=1.0, swa_stress_weight=10.0, dipole_weight=1.0, swa_dipole_weight=1.0, config_type_weights='{Default: 1.0}', optimizer='adam', batch_size=6, valid_batch_size=10, lr=0.01, swa_lr=0.001, weight_decay=5e-07, amsgrad=True, scheduler='ReduceLROnPlateau', lr_factor=0.8, scheduler_patience=50, lr_scheduler_gamma=0.9993, swa=True, start_swa=16, ema=True, ema_decay=0.99, max_num_epochs=20, patience=2048, eval_interval=2, keep_checkpoints=False, restart_latest=True, save_cpu=False, clip_grad=10.0, wandb=False, wandb_project='', wandb_entity='', wandb_name='', wandb_log_hypers=['num_channels', 'max_L', 'correlation', 'lr', 'swa_lr', 'weight_decay', 'batch_size', 'max_num_epochs', 'start_swa', 'energy_weight', 'forces_weight'])
2023-10-09 17:49:47.242 INFO: CUDA version: 11.6, CUDA device: 0
2023-10-09 17:49:47.242 WARNING: Config type weights not specified correctly (malformed node or string: <ast.Name object at 0x14d91352be80>), using Default
2023-10-09 17:49:48.096 INFO: Using isolated atom energies from training file
2023-10-09 17:49:48.150 INFO: Loaded 1106 training configurations from '/tmp/_MACE_fitting_configs.23_ymmq3.xyz'
2023-10-09 17:49:48.151 INFO: Using random 5.0% of training set for validation
2023-10-09 17:49:48.152 INFO: Total number of configurations: train=1051, valid=55, tests=[]
2023-10-09 17:49:48.171 INFO: AtomicNumberTable: (1, 8, 77)
2023-10-09 17:49:48.172 INFO: Atomic energies: [-0.18043406, -0.16369525, -0.4149661]
2023-10-09 17:50:22.641 INFO: WeightedEnergyForcesLoss(energy_weight=1.000, forces_weight=10.000)
2023-10-09 17:50:23.084 INFO: Average number of neighbors: 32.08126860036423
2023-10-09 17:50:23.090 INFO: Selected the following outputs: {'energy': True, 'forces': True, 'virials': False, 'stress': False, 'dipoles': False}
2023-10-09 17:50:23.090 INFO: Building model
2023-10-09 17:50:23.090 INFO: Hidden irreps: 128x0e + 128x1o
2023-10-09 17:50:26.027 INFO: Using stochastic weight averaging (after 16 epochs) with energy weight : 1000.0, forces weight : 1.0 and learning rate : 0.001
2023-10-09 17:50:26.133 INFO: Loading checkpoint: checkpoints/MACE_model_run-123_epoch-8_swa.pt
2023-10-09 17:50:26.197 INFO: ScaleShiftMACE(
  (node_embedding): LinearNodeEmbeddingBlock(
    (linear): Linear(3x0e -> 128x0e | 384 weights)
  )
  (radial_embedding): RadialEmbeddingBlock(
    (bessel_fn): BesselBasis(r_max=4.5, num_basis=8, trainable=False)
    (cutoff_fn): PolynomialCutoff(p=5.0, r_max=4.5)
  )
  (spherical_harmonics): SphericalHarmonics()
  (atomic_energies_fn): AtomicEnergiesBlock(energies=[-0.1804, -0.1637, -0.4150])
  (interactions): ModuleList(
    (0): RealAgnosticInteractionBlock(
      (linear_up): Linear(128x0e -> 128x0e | 16384 weights)
      (conv_tp): TensorProduct(128x0e x 1x0e+1x1o+1x2e+1x3o -> 128x0e+128x1o+128x2e+128x3o | 512 paths | 512 weights)
      (conv_tp_weights): FullyConnectedNet[8, 64, 64, 64, 512]
      (linear): Linear(128x0e+128x1o+128x2e+128x3o -> 128x0e+128x1o+128x2e+128x3o | 65536 weights)
      (skip_tp): FullyConnectedTensorProduct(128x0e+128x1o+128x2e+128x3o x 3x0e -> 128x0e+128x1o+128x2e+128x3o | 196608 paths | 196608 weights)
      (reshape): reshape_irreps()
    )
    (1): RealAgnosticResidualInteractionBlock(
      (linear_up): Linear(128x0e+128x1o -> 128x0e+128x1o | 32768 weights)
      (conv_tp): TensorProduct(128x0e+128x1o x 1x0e+1x1o+1x2e+1x3o -> 256x0e+384x1o+384x2e+256x3o | 1280 paths | 1280 weights)
      (conv_tp_weights): FullyConnectedNet[8, 64, 64, 64, 1280]
      (linear): Linear(256x0e+384x1o+384x2e+256x3o -> 128x0e+128x1o+128x2e+128x3o | 163840 weights)
      (skip_tp): FullyConnectedTensorProduct(128x0e+128x1o x 3x0e -> 128x0e | 49152 paths | 49152 weights)
      (reshape): reshape_irreps()
    )
  )
  (products): ModuleList(
    (0): EquivariantProductBasisBlock(
      (symmetric_contractions): SymmetricContraction(
        (contractions): ModuleList(
          (0): Contraction(
            (contractions_weighting): ModuleList(
              (0): GraphModule()
              (1): GraphModule()
            )
            (contractions_features): ModuleList(
              (0): GraphModule()
              (1): GraphModule()
            )
            (weights): ParameterList(
                (0): Parameter containing: [torch.cuda.DoubleTensor of size 3x4x128 (GPU 0)]
                (1): Parameter containing: [torch.cuda.DoubleTensor of size 3x1x128 (GPU 0)]
            )
            (graph_opt_main): GraphModule()
          )
          (1): Contraction(
            (contractions_weighting): ModuleList(
              (0): GraphModule()
              (1): GraphModule()
            )
            (contractions_features): ModuleList(
              (0): GraphModule()
              (1): GraphModule()
            )
            (weights): ParameterList(
                (0): Parameter containing: [torch.cuda.DoubleTensor of size 3x6x128 (GPU 0)]
                (1): Parameter containing: [torch.cuda.DoubleTensor of size 3x1x128 (GPU 0)]
            )
            (graph_opt_main): GraphModule()
          )
        )
      )
      (linear): Linear(128x0e+128x1o -> 128x0e+128x1o | 32768 weights)
    )
    (1): EquivariantProductBasisBlock(
      (symmetric_contractions): SymmetricContraction(
        (contractions): ModuleList(
          (0): Contraction(
            (contractions_weighting): ModuleList(
              (0): GraphModule()
              (1): GraphModule()
            )
            (contractions_features): ModuleList(
              (0): GraphModule()
              (1): GraphModule()
            )
            (weights): ParameterList(
                (0): Parameter containing: [torch.cuda.DoubleTensor of size 3x4x128 (GPU 0)]
                (1): Parameter containing: [torch.cuda.DoubleTensor of size 3x1x128 (GPU 0)]
            )
            (graph_opt_main): GraphModule()
          )
        )
      )
      (linear): Linear(128x0e -> 128x0e | 16384 weights)
    )
  )
  (readouts): ModuleList(
    (0): LinearReadoutBlock(
      (linear): Linear(128x0e+128x1o -> 1x0e | 128 weights)
    )
    (1): NonLinearReadoutBlock(
      (linear_1): Linear(128x0e -> 16x0e | 2048 weights)
      (non_linearity): Activation [x] (16x0e -> 16x0e)
      (linear_2): Linear(16x0e -> 1x0e | 16 weights)
    )
  )
  (scale_shift): ScaleShiftBlock(scale=0.943357, shift=0.000000)
)
2023-10-09 17:50:26.202 INFO: Number of parameters: 751888
2023-10-09 17:50:26.203 INFO: Optimizer: Adam (
Parameter Group 0
    amsgrad: True
    betas: (0.9, 0.999)
    capturable: False
    eps: 1e-08
    foreach: None
    initial_lr: 0.01
    lr: 0.001
    maximize: False
    name: embedding
    swa_lr: 0.001
    weight_decay: 0.0

Parameter Group 1
    amsgrad: True
    betas: (0.9, 0.999)
    capturable: False
    eps: 1e-08
    foreach: None
    initial_lr: 0.01
    lr: 0.001
    maximize: False
    name: interactions_decay
    swa_lr: 0.001
    weight_decay: 5e-07

Parameter Group 2
    amsgrad: True
    betas: (0.9, 0.999)
    capturable: False
    eps: 1e-08
    foreach: None
    initial_lr: 0.01
    lr: 0.001
    maximize: False
    name: interactions_no_decay
    swa_lr: 0.001
    weight_decay: 0.0

Parameter Group 3
    amsgrad: True
    betas: (0.9, 0.999)
    capturable: False
    eps: 1e-08
    foreach: None
    initial_lr: 0.01
    lr: 0.001
    maximize: False
    name: products
    swa_lr: 0.001
    weight_decay: 5e-07

Parameter Group 4
    amsgrad: True
    betas: (0.9, 0.999)
    capturable: False
    eps: 1e-08
    foreach: None
    initial_lr: 0.01
    lr: 0.001
    maximize: False
    name: readouts
    swa_lr: 0.001
    weight_decay: 0.0
)
2023-10-09 17:50:26.203 INFO: Using gradient clipping with tolerance=10.000
2023-10-09 17:50:26.203 INFO: Started training
```

**Comment by davkovacs** [comment]
And you get the error message after it starts training? 
I have never seen something like this, @ilyes319 any ideas? It seems like the problem is with the optimizer device?

**Comment by ilyes319** [comment]
I have never seen that problem. Could you tell me your pytorch version?
Also, are you sure you have restarted with the same pytorch version as the one you started training?

**Comment by bapatist** [comment]
Thanks for the comments. I am not sure what could be the reason but will ensure the pytorch versions. I might have to clean recompile because others using the same cluster in my department don't have this issue. I will write back an update in the next few days on what I find out.

**Comment by bapatist** [comment]
Okay after recompiling in a slightly different environment the issue got resolved! I suspect it was the improper version of the `cudnn` package which caused the problem specifically while restart-fitting (weird). Closing the issue now, thanks!
