### ISSUE TITLE
Error while Evaluation of model. Please help

### ISSUE THREAD

**Issue by Amitcuhp** [ACEsuit/mace#191]
RuntimeError: expected scalar type Double but found Float

**Comment by Amitcuhp** [comment]
Traceback (most recent call last):
  File "/home/Raman/mace/scripts/eval_configs.py", line 151, in <module>
    main()
  File "/home/Raman/mace/scripts/eval_configs.py", line 108, in main
    output = model(batch.to_dict(), compute_stress=args.compute_stress)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Raman/miniconda3/envs/mace-gpu/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Raman/miniconda3/envs/mace-gpu/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Raman/miniconda3/envs/mace-gpu/lib/python3.11/site-packages/mace/modules/models.py", line 295, in forward
    node_e0 = self.atomic_energies_fn(data["node_attrs"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Raman/miniconda3/envs/mace-gpu/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Raman/miniconda3/envs/mace-gpu/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Raman/miniconda3/envs/mace-gpu/lib/python3.11/site-packages/mace/modules/blocks.py", line 137, in forward
    return torch.matmul(x, self.atomic_energies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: expected scalar type Double but found Float

**Comment by davkovacs** [comment]
The eval config has an argument `--default_dtype` Make sure to set that correctly to how the model was trained. Seems like your model was trained using float32 and default of the evaluation code is float64.

**Comment by Amitcuhp** [comment]
Thank you very much
