### ISSUE TITLE
The code for plot_train.py not working after giving the PATH. What I am doing wrong help ?

### ISSUE THREAD

**Issue by Amitcuhp** [ACEsuit/mace#192]
Help

**Comment by Amitcuhp** [comment]
Traceback (most recent call last):
  File "/home/Raman/mace/scripts/plot_train.py", line 186, in <module>
    main()
  File "/home/Raman/mace/scripts/plot_train.py", line 175, in main
    data = pd.DataFrame(
           ^^^^^^^^^^^^^
  File "/home/Raman/miniconda3/envs/mace-gpu/lib/python3.11/site-packages/pandas/core/frame.py", line 801, in __init__
    data = list(data)
           ^^^^^^^^^^
  File "/home/Raman/mace/scripts/plot_train.py", line 178, in <genexpr>
    for results in parse_training_results(path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Raman/mace/scripts/plot_train.py", line 55, in parse_training_results
    d["name"] = run_info.name
    ~^^^^^^^^
TypeError: 'int' object does not support item assignment

**Comment by ilyes319** [comment]
what path are you giving exactly?

**Comment by Amitcuhp** [comment]
!python3 /home/Raman/mace/scripts/plot_train.py \\\n",
    "    --path=/home/Raman/amit/MAce/A1 "
