### ISSUE TITLE
error in altest model 

### ISSUE THREAD

**Issue by Asif-Iqbal-Bhatti** [ACEsuit/mace#218]
Hallo,

#!/usr/bin/env python

from mace.calculators import MACECalculator
from ase import Atoms
from ase.optimize import BFGS
from ase.constraints import ExpCellFilter

atoms = Atoms("NaCl")
calculator = MACECalculator(
  model_paths='2023-08-14-mace-universal.model',
  device='cuda',
)
atoms.calc = calculator
#============== Initial state
ucf = ExpCellFilter(atoms)
qn = BFGS(ucf, trajectory='INI_00.traj')
qn.run(fmax = 0.001)

When running this simple example with the latest trained model I got this error:

'''
/home/****/miniconda3/lib/python3.10/site-packages/torch/overrides.py:110: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  torch.has_cuda,
/home/****/miniconda3/lib/python3.10/site-packages/torch/overrides.py:111: UserWarning: 'has_cudnn' is deprecated, please use 'torch.backends.cudnn.is_available()'
  torch.has_cudnn,
/home/****/miniconda3/lib/python3.10/site-packages/torch/overrides.py:117: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  torch.has_mps,
/home/****/miniconda3/lib/python3.10/site-packages/torch/overrides.py:118: UserWarning: 'has_mkldnn' is deprecated, please use 'torch.backends.mkldnn.is_available()'
  torch.has_mkldnn,
Atoms(symbols='NaCl', pbc=False, calculator=MACECalculator(...))
Traceback (most recent call last):
  File "/mnt/c/Users/****/Desktop/./mace_model.py", line 32, in <module>
    qn.run(fmax = 0.001)
  File "/home/****/miniconda3/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
    return Dynamics.run(self)
  File "/home/****/miniconda3/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
    for converged in Dynamics.irun(self):
  File "/home/****/miniconda3/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
    self.atoms.get_forces()
  File "/home/****/miniconda3/lib/python3.10/site-packages/ase/constraints.py", line 2614, in get_forces
    forces = UnitCellFilter.get_forces(self, **kwargs)
  File "/home/****/miniconda3/lib/python3.10/site-packages/ase/constraints.py", line 2434, in get_forces
    stress = self.atoms.get_stress(**kwargs)
  File "/home/****/miniconda3/lib/python3.10/site-packages/ase/atoms.py", line 820, in get_stress
    stress = self._calc.get_stress(self)
  File "/home/****/miniconda3/lib/python3.10/site-packages/ase/calculators/abc.py", line 26, in get_stress
    return self.get_property('stress', atoms)
  File "/home/****/miniconda3/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/home/****/miniconda3/lib/python3.10/site-packages/mace/calculators/mace.py", line 182, in calculate
    node_e0 = self.models[0].atomic_energies_fn(batch["node_attrs"])
  File "/home/****/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/****/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/****/miniconda3/lib/python3.10/site-packages/mace/modules/blocks.py", line 137, in forward
    return torch.matmul(x, self.atomic_energies)
RuntimeError: expected scalar type Double but found Float
'''

I don't understand why I am getting this. I ran the chgnet model, but it was running without any errors on Cuda.

Asif

**Comment by davkovacs** [comment]
Just add to the MACECalculator the keyword default_dtype=“float32”.

**Comment by Asif-Iqbal-Bhatti** [comment]
Thanks it is working now
