### ISSUE TITLE
RuntimeError: tensors must be on the same device (torch=2.1 python=3.11)

### ISSUE THREAD

**Issue by ale99WGiais** [ACEsuit/mace#219]
**Describe the bug**

I get the following error when trying to execute run_train.py
```

2023-11-12 18:26:36.093 INFO: Using gradient clipping with tolerance=10.000
2023-11-12 18:26:36.093 INFO: Started training
Traceback (most recent call last):
  File "/home2/s5845513/mace/scripts/run_train.py", line 6, in <module>
    main()
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.11/site-packages/mace/cli/run_train.py", line 490, in main
    tools.train(
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.11/site-packages/mace/tools/train.py", line 92, in train
    _, opt_metrics = take_step(
                     ^^^^^^^^^^
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.11/site-packages/mace/tools/train.py", line 253, in take_step
    optimizer.step()
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.11/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.11/site-packages/torch/optim/optimizer.py", line 373, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.11/site-packages/torch/optim/optimizer.py", line 76, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.11/site-packages/torch/optim/adam.py", line 163, in step
    adam(
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.11/site-packages/torch/optim/adam.py", line 311, in adam
    func(params,
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.11/site-packages/torch/optim/adam.py", line 474, in _multi_tensor_adam
    grouped_tensors = Optimizer._group_tensors_by_device_and_dtype(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.11/site-packages/torch/optim/optimizer.py", line 397, in _group_tensors_by_device_and_dtype
    return _group_tensors_by_device_and_dtype(tensorlistlist, with_indices)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.11/site-packages/torch/utils/_foreach_utils.py", line 42, in _group_tensors_by_device_and_dtype
    torch._C._group_tensors_by_device_and_dtype(tensorlistlist, with_indices).items()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
RuntimeError: Tensors of the same index must be on the same device and the same dtype except `step` tensors that can be CPU and float32 notwithstanding

**To Reproduce**

```
python ~/mace/scripts/run_train.py \
    --name="MACE_model" \
    --train_file="../Ogata_DB.xyz" \
    --valid_fraction=0.05 \
    --config_type_weights='{"Default":1.0}' \
    --E0s='{1:-13.663181292231226, 6:-1029.2809654211628, 7:-1484.1187695035828, 8:-2042.0330099956639, 26:-2042.0330099956639}' \
    --model="MACE" \
    --hidden_irreps='128x0e + 128x1o' \
    --r_max=5.0 \
    --batch_size=1 \
    --max_num_epochs=1500 \
    --swa \
    --start_swa=1200 \
    --ema \
    --ema_decay=0.99 \
    --amsgrad \
    --restart_latest \
    --device=cuda

```
To create the environment: 

```
1. conda install pytorch torchvision torchaudio pytorch-cuda -c pytorch -c nvidia
2. conda install numpy scipy matplotlib ase opt_einsum prettytable pandas e3nn
3. pip install mace/
```

[export conda list.txt](https://github.com/ACEsuit/mace/files/13328696/export.conda.list.txt)

**Expected behavior**

Expected to train MACE :) 

**Server:**

```
NAME="Rocky Linux"
VERSION="8.8 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.8 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
```

![Screenshot 2023-11-12 183648](https://github.com/ACEsuit/mace/assets/9408047/12b417a9-81ac-403c-bfa9-ab4249e6ea29)

**Comment by ilyes319** [comment]
Hey, can you tell me what is the torch version that is getting installed?

**Comment by ale99WGiais** [comment]
Hey, it is 2.1.0 :)

**Comment by ilyes319** [comment]
Can you try to install 2.0 please?

**Comment by ale99WGiais** [comment]
2.0 seems to work :)

**Comment by ilyes319** [comment]
Ok we need to add to the readme that 2.1 is not working.
