### ISSUE TITLE
KeyError: 'forces_var' in the active_learning_md.py

### ISSUE THREAD

**Issue by nitbha007** [ACEsuit/mace#220]
Hello, I encountered a key error 'forces_var' while running the active learning script. In the MACE calculator, 'energy_var' is defined but I could not locate the 'forces_var' in the calculator code. Hence the error arises. I did find 'foces_comm', so I used it but it again throw me a shape error.  Any suggestions? Thank you!

```
Traceback (most recent call last):
  File "/Users/bhatian1/Library/CloudStorage/OneDrive-AaltoUniversity/work_triton/MACE/test/MD/AL/Al_code/active_learning_md.py", line 183, in <module>
    main()
  File "/Users/bhatian1/Library/CloudStorage/OneDrive-AaltoUniversity/work_triton/MACE/test/MD/AL/Al_code/active_learning_md.py", line 179, in main
    dyn.run(NSTEPS)
  File "/Users/bhatian1/Library/CloudStorage/OneDrive-AaltoUniversity/work_triton/MACE/mace-venv/lib/python3.9/site-packages/ase/md/md.py", line 137, in run
    return Dynamics.run(self)
  File "/Users/bhatian1/Library/CloudStorage/OneDrive-AaltoUniversity/work_triton/MACE/mace-venv/lib/python3.9/site-packages/ase/optimize/optimize.py", line 156, in run
    for converged in Dynamics.irun(self):
  File "/Users/bhatian1/Library/CloudStorage/OneDrive-AaltoUniversity/work_triton/MACE/mace-venv/lib/python3.9/site-packages/ase/optimize/optimize.py", line 129, in irun
    self.call_observers()
  File "/Users/bhatian1/Library/CloudStorage/OneDrive-AaltoUniversity/work_triton/MACE/mace-venv/lib/python3.9/site-packages/ase/optimize/optimize.py", line 108, in call_observers
    function(*args, **kwargs)
  File "/Users/bhatian1/Library/CloudStorage/OneDrive-AaltoUniversity/work_triton/MACE/test/MD/AL/Al_code/active_learning_md.py", line 94, in printenergy
    np.max(np.linalg.norm(a.calc.results["forces_var"], axis=1)),
KeyError: 'forces_var'
```

**Comment by ilyes319** [comment]
Hey, thank you for pointing out, I think we remove that key to just output the committee. We should update the script to compute the variance outside of the calculator now.

**Comment by davkovacs** [comment]
Could you please check if this fixes it? 
https://github.com/ACEsuit/mace/pull/221

**Comment by nitbha007** [comment]
Yes, it works now. Thank you. 
Is there an existing implementation with MACE for selecting uncertain data points, adding them to the original dataset, and then retraining the model, similar to the standard active learning approach?

**Comment by davkovacs** [comment]
I think you can use the active learning script we have as an ingredient for such a script. But we do not provide one as you need to choose your DFT code, launch calculation etc. 

Can I close this issue?

**Comment by nitbha007** [comment]
Sure. This is already of much help. I can build on it. You can close the issue!
Thank you.
