### ISSUE TITLE
"UnboundLocalError: local variable 'last_ir' referenced before assignment" when training with --max_L > --max_ell

### ISSUE THREAD

**Issue by ale99WGiais** [ACEsuit/mace#227]
**Describe the bug**

Obtained `UnboundLocalError: local variable 'last_ir' referenced before assignment` when trying to train mace passing max_L > max_ell. 

**To Reproduce**

`python ~/mace/scripts/run_train.py  --name="MACE_model"  --train_file="/home2/s5845513/data/iron_test/Ogata_DB.xyz"  --model="MACE"  --device=cuda   --max_L=2   --num_channels=40   --max_ell=1`

**Expected behavior**

If it is right that a model cannot have max_L > max_ell, I would like to receive an informative error message explaining the problem. 

**Screenshots**

`Traceback (most recent call last):
  File "/home2/s5845513/mace/scripts/run_train.py", line 6, in <module>
    main()
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.10/site-packages/mace/cli/run_train.py", line 256, in main
    model = modules.ScaleShiftMACE(
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.10/site-packages/mace/modules/models.py", line 276, in __init__
    super().__init__(**kwargs)
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.10/site-packages/mace/modules/models.py", line 115, in __init__
    prod = EquivariantProductBasisBlock(
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.10/site-packages/mace/modules/blocks.py", line 183, in __init__
    self.symmetric_contractions = SymmetricContraction(
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.10/site-packages/mace/modules/symmetric_contraction.py", line 71, in __init__
    Contraction(
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.10/site-packages/mace/modules/symmetric_contraction.py", line 104, in __init__
    U_matrix = U_matrix_real(
  File "/home2/s5845513/miniconda3/envs/mace/lib/python3.10/site-packages/mace/tools/cg.py", line 130, in U_matrix_real
    out += [last_ir, stack]
UnboundLocalError: local variable 'last_ir' referenced before assignment`

**Comment by ilyes319** [comment]
Indeed this is not possible mathematically. Might be good to add an error in run_train
