### ISSUE TITLE
can't create MACECalculator

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/mace#362]
As per @ilyes319 's request, I switched to the `develop` branch, and now I can't even create a `MACECalculator`

```
Traceback (most recent call last):
  File "/home/cluster2/bernstei/src/work/NiOxHy/fit_iterative_stage_010/./fit_iter_010_MD_sample.py", line 42, in <module>                                
    from mace.calculators import MACECalculator
  File "/home/cluster2/bernstei/.local/lib/python3.9/site-packages/mace/calculators/__init__.py", line 1, in <module>                                     
    from .foundations_models import mace_anicc, mace_mp, mace_off
  File "/home/cluster2/bernstei/.local/lib/python3.9/site-packages/mace/calculators/foundations_models.py", line 213, in <module>                         
    model_path: str | Path = None,
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

Is it because I'm still using python 3.9?

**Comment by ilyes319** [comment]
fixed that if you can try again

**Comment by bernstei** [comment]
Looks good now.
