### ISSUE TITLE
SWA doesn't work when patience triggers loop exit

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/mace#48]
If the initial optimization is stopped by `patience`, the SWA phase does not run. Instead, it fails with the error message
```
Traceback (most recent call last):
  File "/p/home/noamb/.local/bin/mace_fit", line 8, in <module>
    sys.exit(main())
  File "/p/home/noamb/.local/lib/python3.8/site-packages/mace/cli/run_train.py", line 485, in main
    epoch = checkpoint_handler.load_latest(
  File "/p/home/noamb/.local/lib/python3.8/site-packages/mace/tools/checkpoint.py", line 207, in load_latest
    result = self.io.load_latest(swa=swa, device=device)
  File "/p/home/noamb/.local/lib/python3.8/site-packages/mace/tools/checkpoint.py", line 168, in load_latest
    path = self._get_latest_checkpoint_path(swa=swa)
  File "/p/home/noamb/.local/lib/python3.8/site-packages/mace/tools/checkpoint.py", line 142, in _get_latest_checkpoint_path
    latest_checkpoint_info = max(
```

stdout file is attached
[mace_fit_stdout.txt](https://github.com/ACEsuit/mace/files/10013246/mace_fit_stdout.txt)

**Comment by davkovacs** [comment]
Should be solved in https://github.com/ACEsuit/mace/pull/35
