### ISSUE TITLE
Vectorized Hessians seem not to work

### ISSUE THREAD

**Issue by Nilsgoe** [ACEsuit/mace#488]
First of all thank you for "mergeing" my pull request in a slightly edited way.

If i want to use the vectorized implementation it seems not to work. 
The error message is:
```
Using Materials Project MACE for MACECalculator with /home/ngoen/.cache/mace/5yyxdm76
Using float64 for MACECalculator, which is slower but more accurate. Recommended for geometry optimization.
-369.35988575999255
/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/torch/autograd/__init__.py:303: UserWarning: FALLBACK path has been taken inside: runCudaFusionGroup. This is an indication that codegen Failed for some reason.
To debug try disable codegen fallback path via setting the env variable `export PYTORCH_NVFUSER_DISABLE=fallback`
 (Triggered internally at ../third_party/nvfuser/csrc/manager.cpp:335.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/mace/modules/utils.py", line 136, in compute_hessians_vmap
    gradient = torch.vmap(get_vjp, in_dims=0, out_dims=0, chunk_size=chunk_size)(
  File "/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/torch/_functorch/vmap.py", line 430, in wrapped
    return _chunked_vmap(func, flat_in_dims, chunks_flat_args,
  File "/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/torch/_functorch/vmap.py", line 520, in _chunked_vmap
    _flat_vmap(
  File "/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/torch/_functorch/vmap.py", line 39, in fn
    return f(*args, **kwargs)
  File "/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/torch/_functorch/vmap.py", line 619, in _flat_vmap
    batched_outputs = func(*batched_inputs, **kwargs)
  File "/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/mace/modules/utils.py", line 123, in get_vjp
    return torch.autograd.grad(
  File "/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 303, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: shape '[0, 2, 1]' is invalid for input of size 1024



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/home/ngoen/Documents/torch_testing/large_test.py", line 100, in <module>
    h_autograd=calc.get_hessian(atoms=initial)#vectorized_autograd")
  File "/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/mace/calculators/mace.py", line 320, in get_hessian
    hessians = [
  File "/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/mace/calculators/mace.py", line 321, in <listcomp>
    model(
  File "/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/mace/modules/models.py", line 395, in forward
    forces, virials, stress, hessian = get_outputs(
  File "/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/mace/modules/utils.py", line 211, in get_outputs
    hessian = compute_hessians_vmap(forces, positions)
  File "/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/mace/modules/utils.py", line 140, in compute_hessians_vmap
    gradient = compute_hessians_loop(forces, positions)
  File "/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/mace/modules/utils.py", line 154, in compute_hessians_loop
    hess_row = torch.autograd.grad(
  File "/work/home/ngoen/mace_h-venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 303, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: stack.size() >= frames.back().function->n_inputs INTERNAL ASSERT FAILED at "../torch/csrc/jit/runtime/interpreter.cpp":241, please report a bug to PyTorch. 
```
The code I am running is:

```
from mace.calculators import mace_mp
from ase import build
import numpy as np
from ase.build import fcc111,

initial = fcc111('Pt', size=(4,4, 4), vacuum=10.0, orthogonal=True)
calc = mace_mp(model="medium", dispersion=False, default_dtype="float64",device='cuda', )           #device='cpu')

initial.calc = calc
e0=initial.get_potential_energy()
print(e0)
h_autograd=calc.get_hessian(atoms=initial)#vectorized_autograd")
print("h:",h_autograd)
```
I am using this packages and versions:

```
Package             Version
------------------- -----------
ase                 3.23.0
e3nn                0.4.4
mace-torch          0.3.5
pip                 23.0.1
torch               2.0.1+cu118
torch-ema           0.3
torchaudio          2.0.2
torchmetrics        1.4.0.post0
torchvision         0.15.2
```
The error seems still to come from the jit.compile and vmap combination.
The loop implementation in the code works totally fine for me.
I am aware of the problem for the vectorized I was using, comes from the sphirical_harmonics of e3nn this could also be the case here.

Does it work for a different setup of versions? If yes what setup should i choose.

**Comment by ilyes319** [comment]
Can you update your torch version to the latest one. At the 2.0.1, torch.vmap was still experimental.

**Comment by ilyes319** [comment]
Works fine on colab with Pytorch 2.3.0: https://colab.research.google.com/drive/1GJETYYW8iUpDeyJ7p0j44FkjOM7gbYAm#scrollTo=mxSX_Y1lRR7p

**Comment by Nilsgoe** [comment]
I tested it  with torch 2.31. and yes it works. Great!

**Comment by ilyes319** [comment]
What GPU are you using?

**Comment by Nilsgoe** [comment]
It's a  "NVIDIA A100 80GB PCIe".

**Comment by ilyes319** [comment]
Can confirm that it is working on CPU?

**Comment by Nilsgoe** [comment]
Yes with CPU it works.
But when I am trying it in [colab](https://colab.research.google.com/drive/1hmrx3FI2EAUtJ62wk6EA3OPxB9HUUnuk?usp=sharing) with print statements added at the try/except:
```
try:
        print("vmap")
        chunk_size = 1 if num_elements < 64 else 16
        gradient = torch.vmap(get_vjp, in_dims=0, out_dims=0, chunk_size=chunk_size)(
            I_N
        )[0]
except RuntimeError:
        print("loop")
        gradient = compute_hessians_loop(forces, positions)
```
I am still printing vmap and loop which tells me that it falls back to the  loop implementation.

**Comment by ilyes319** [comment]
Can you confirm it is working on GPU when you remove the line that computes the E0.

**Comment by Nilsgoe** [comment]
Yes it prints then once only vmap now when I am running it on my own GPU (in the colab it seems to not do that). But when i am running it like this:
```
for i in range(5):
    s=time.time()
    h_autograd=calc.get_hessian(atoms=initial)
    e=time.time()
    print(f"This system needs {e-s} seconds")
```
it falls back to the loop implementation
