### ISSUE TITLE
ASE dipole calculation

### ISSUE THREAD

**Issue by J-Fabila** [ACEsuit/mace#610]
Hello,

I’m trying to run an MD simulation using the EnergyDipolesMACE model, but when I execute this snippet, I encounter an error stating that the dipole property is not implemented (see below). Am I missing something, or is this feature not yet implemented?

```
mace_calc = MACECalculator(model_paths=['MACE_dip/mace03_run-123.model'], device='cuda', default_dtype="float32")
dyn = Langevin(atoms,timestep=1.0 * units.fs, temperature_K=temperatura,friction=0.1) # / units.fs)
temperatures = []
dipoles = []
forces = []
energies = []

for i in range(1000):
    dyn.step()
    dyn.atoms.write(output_file, append=True)
    temperatures.append(dyn.atoms.get_temperature())
    #atoms.get_dipole_moment()
    dipole.append(dyn.atoms.get_dipole_moment())
    forces.append(dyn.atoms.get_forces())
    energies.append(dyn.atoms.get_potential_energy())
    print(i,temperatures[i])

```

```

Traceback (most recent call last):
  File "/home/jorge/work_dir/mace/dm_nose_hoover.py", line 46, in <module>
    atoms.get_dipole_moment()
  File "/home/jorge/anaconda3/envs/torch/lib/python3.11/site-packages/ase/atoms.py", line 927, in get_dipole_moment
    return self._calc.get_dipole_moment(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/anaconda3/envs/torch/lib/python3.11/site-packages/ase/calculators/abc.py", line 42, in get_dipole_moment
    return self.get_property('dipole', atoms)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jorge/anaconda3/envs/torch/lib/python3.11/site-packages/ase/calculators/calculator.py", line 517, in get_property
    raise PropertyNotImplementedError(
ase.calculators.calculator.PropertyNotImplementedError: dipole property not implemented
```

**Comment by ilyes319** [comment]
You need to add to the calculator: `model_type="EnergyDipoleMACE"`
