### ISSUE TITLE
preprocess_data.py error: 'Namespace' object has no attribute 'work_dir'

### ISSUE THREAD

**Issue by axgmz** [ACEsuit/mace#614]
Hello,
I am experiencing a surprising bug with the `preprocess_data.py` script.
It is similar to errors that can occur when the way arguments are parsed/attributed has been changed recently, but the script has not been updated accordingly.
Thanks for any help in solving this problem!

**Describe the bug**
I have installed the latest version of MACE (from the `main` branch), it works well for training, and also with Lammps. I need to pre-process a (moderately) large dataset with `mace/scripts/preprocess_data.py`. It does not run and returns this error immediately:
```
Traceback (most recent call last):
  File "/home/user/mace_install/mace/scripts/preprocess_data.py", line 6, in <module>
    main()
  File "/home/user/mace_install/lib/python3.9/site-packages/mace/cli/preprocess_data.py", line 123, in main
    run(args)
  File "/home/user/mace_install/lib/python3.9/site-packages/mace/cli/preprocess_data.py", line 158, in run
    work_dir=args.work_dir,
AttributeError: 'Namespace' object has no attribute 'work_dir'
```

**To Reproduce**
1. Install MACE (I tried on 2 different supercomputers)
2. Activate MACE
3. Run the `preprocess_data.py` following precisely the documentation: [https://mace-docs.readthedocs.io/en/latest/guide/multipreprocessing.html](https://mace-docs.readthedocs.io/en/latest/guide/multipreprocessing.html)
4. See error above

**Expected behavior**
I would expect the script to run and pre-process the dataset as indicated in the manual: https://mace-docs.readthedocs.io/en/latest/guide/multipreprocessing.html](https://mace-docs.readthedocs.io/en/latest/guide/multipreprocessing.html)

**Installed on a supercomputer:**
 - Linux environment
 - A100 GPUs with AMD EPYC CPUs
 - or V100 GPUs with Intel Cascade Lake 6248 CPUs
 - Installed on Sept. 23 and Sept. 30, 2024 (with `git clone` from the main branch)

**Comment by ilyes319** [comment]
Hey that looks like a bug indeed, thank you for reporting, will fix it.

**Comment by ilyes319** [comment]
That should be fixed in main if you can try again.

**Comment by axgmz** [comment]
I just tested it and this part seems to be fixed. Thanks for your quick response!
However, I then encountered an additional new bug:
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/user/mace_install_20241001/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/user/mace_install_20241001/mace/mace/cli/preprocess_data.py", line 42, in compute_stats_target
    avg_num_neighbors, mean, std = compute_statistics(train_loader, atomic_energies)
  File "/home/user/mace_install_20241001/lib/python3.9/site-packages/mace/modules/utils.py", line 408, in compute_statistics
    torch.sqrt(scatter_mean(src=torch.square(forces), index=head, dim=0))
  File "/home/user/mace_install_20241001/lib/python3.9/site-packages/mace/tools/scatter.py", line 95, in scatter_mean
    out = scatter_sum(src, index, dim, out, dim_size)
  File "/home/user/mace_install_20241001/lib/python3.9/site-packages/mace/tools/scatter.py", line 36, in scatter_sum
    index = _broadcast(index, src, dim)
  File "/home/user/mace_install_20241001/lib/python3.9/site-packages/mace/tools/scatter.py", line 23, in _broadcast
    src = src.expand_as(other)
RuntimeError: The expanded size of the tensor (62519) must match the existing size (144) at non-singleton dimension 0.  Target sizes: [62519, 3].  Tensor sizes: [144, 1]
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/mace_install_20241001/mace/mace/cli/preprocess_data.py", line 273, in <module>
    main()
  File "/home/user/mace_install_20241001/mace/mace/cli/preprocess_data.py", line 123, in main
    run(args)
  File "/home/user/mace_install_20241001/mace/mace/cli/preprocess_data.py", line 217, in run
    avg_num_neighbors, mean, std=pool_compute_stats(_inputs)
  File "/home/user/mace_install_20241001/mace/mace/cli/preprocess_data.py", line 68, in pool_compute_stats
    results = [r.get() for r in tqdm.tqdm(re)]
  File "/home/user/mace_install_20241001/mace/mace/cli/preprocess_data.py", line 68, in <listcomp>
    results = [r.get() for r in tqdm.tqdm(re)]
  File "/home/user/mace_install_20241001/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
RuntimeError: The expanded size of the tensor (62519) must match the existing size (144) at non-singleton dimension 0.  Target sizes: [62519, 3].  Tensor sizes: [144, 1]
```
For reference, I also installed v.0.3.6 as per your recommendation, and it works fine and generates the h5 files from my xyz.

**Comment by ilyes319** [comment]
I have fixed that in the latest main, can you test again?

**Comment by axgmz** [comment]
Tested, and it works fine. Thanks!
