### ISSUE TITLE
mismatch of 0e & 1o feature length breaks the model

### ISSUE THREAD

**Issue by stenczelt** [ACEsuit/mace#63]
**Describe the bug**
Training of a model with different length of `0e` and `1o` features breaks the network after construction. Happens on the current development branch.

Should this be prevented by validating the inputs to the training script (i.e. if there is any conceptual limitation against it) or be just working?

I have tested withe the following options:
- `17x0e + 13x1o` - two primes
- `17x0e + 51x1o` - x + 5*x
- `17x0e + 34x1o`-  x + 2*x
- `17x0e + 169x1o` - x + x * x
- `16x0e + 32x1o` - 16 + 16 * 2

**To Reproduce**
1. try training a model with `--hidden_irreps="Ax0e + Bx1o"` having `A  != B`

**Expected behavior**
One of the following
- exception raised upon validation of training script input / model construction
- the model just working as with 

Try by running the following:
```
#!/bin/bash

python ../scripts/run_train.py --name="MACE-prime-sizes"
  --train_file="structures/train.xyz" \
  --valid_fraction=0.05 \
  --test_file="structures/test.xyz" \
  --E0s="average" \
  --model="ScaleShiftMACE" \
  --hidden_irreps="17x0e + 13x1o" \
  --r_max=4.0 \
  --batch_size=5 \
  --max_num_epochs=10 \
  --ema \
  --ema_decay=0.99 \
  --amsgrad \
  --default_dtype="float64" \
  --seed=0
```

Exception:
```
2023-01-02 18:44:27.343 INFO: Started training
Traceback (most recent call last):
  File "/Users/tks32/work/mace/scripts/run_train.py", line 488, in <module>
    main()
  File "/Users/tks32/work/mace/scripts/run_train.py", line 427, in main
    tools.train(
  File "/Users/tks32/work/mace/mace/tools/train.py", line 69, in train
    _, opt_metrics = take_step(
  File "/Users/tks32/work/mace/mace/tools/train.py", line 211, in take_step
    output = model(
  File "/Users/tks32/opt/miniconda3/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/tks32/work/mace/mace/modules/models.py", line 281, in forward
    node_feats = product(
  File "/Users/tks32/opt/miniconda3/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/tks32/work/mace/mace/modules/blocks.py", line 181, in forward
    return self.linear(node_feats) + sc
  File "/Users/tks32/opt/miniconda3/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/tks32/opt/miniconda3/envs/mace/lib/python3.9/site-packages/e3nn/o3/_linear.py", line 276, in forward
    return self._compiled_main(features, weight, bias)
  File "/Users/tks32/opt/miniconda3/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "<eval_with_key>.45", line 8, in forward
    getitem = getattr_1[slice(None, -1, None)];  getattr_1 = None
    add = getitem + (56,);  getitem = None
    reshape = x.reshape(-1, 56);  x = None
              ~~~~~~~~~ <--- HERE
    getattr_2 = reshape.shape
    getitem_1 = getattr_2[0];  getattr_2 = None
RuntimeError: shape '[-1, 56]' is invalid for input of size 21080
```

Full log
```
/Users/tks32/opt/miniconda3/envs/mace/bin/python /Users/tks32/work/mace/scripts/run_train.py --name=MACE-prime-sizes --train_file=structures/train.xyz --valid_fraction=0.05 --test_file=structures/test.xyz --E0s=average --model=ScaleShiftMACE --hidden_irreps=17x0e + 13x1o --r_max=4.0 --batch_size=5 --max_num_epochs=10 --ema --ema_decay=0.99 --amsgrad --default_dtype=float64 --seed=3 
2023-01-02 18:44:25.298 INFO: MACE version: 0.1.0
2023-01-02 18:44:25.298 INFO: Configuration: Namespace(name='MACE-prime-sizes', seed=3, log_dir='logs', model_dir='.', checkpoints_dir='checkpoints', results_dir='results', downloads_dir='downloads', device='cpu', default_dtype='float64', log_level='INFO', error_table='PerAtomRMSE', model='ScaleShiftMACE', r_max=4.0, num_radial_basis=8, num_cutoff_basis=5, interaction='RealAgnosticResidualInteractionBlock', interaction_first='RealAgnosticResidualInteractionBlock', max_ell=3, correlation=3, num_interactions=2, MLP_irreps='16x0e', hidden_irreps='17x0e + 13x1o', gate='silu', scaling='rms_forces_scaling', avg_num_neighbors=1, compute_avg_num_neighbors=True, compute_stress=False, compute_forces=True, train_file='structures/train.xyz', valid_file=None, valid_fraction=0.05, test_file='structures/test.xyz', E0s='average', energy_key='energy', forces_key='forces', virials_key='virials', stress_key='stress', dipole_key='dipole', charges_key='charges', loss='weighted', forces_weight=10.0, swa_forces_weight=1.0, energy_weight=1.0, swa_energy_weight=1000.0, virials_weight=1.0, stress_weight=1.0, dipole_weight=1.0, swa_dipole_weight=1.0, config_type_weights='{"Default":1.0}', optimizer='adam', batch_size=5, valid_batch_size=10, lr=0.01, swa_lr=0.001, weight_decay=5e-07, amsgrad=True, scheduler='ReduceLROnPlateau', lr_factor=0.8, scheduler_patience=50, lr_scheduler_gamma=0.9993, swa=False, start_swa=None, ema=True, ema_decay=0.99, max_num_epochs=10, patience=2048, eval_interval=2, keep_checkpoints=False, restart_latest=False, save_cpu=False, clip_grad=10.0)
2023-01-02 18:44:25.299 INFO: Using CPU
2023-01-02 18:44:25.344 INFO: Loaded 20 training configurations from 'structures/train.xyz'
2023-01-02 18:44:25.344 INFO: Using random 5.0% of training set for validation
2023-01-02 18:44:25.440 INFO: Loaded 137 test configurations from 'structures/test.xyz'
2023-01-02 18:44:25.440 INFO: Total number of configurations: train=19, valid=1, tests=[Default: 137]
2023-01-02 18:44:25.441 INFO: AtomicNumberTable: (1, 26)
2023-01-02 18:44:25.441 INFO: Atomic Energies not in training file, using command line argument E0s
2023-01-02 18:44:25.441 INFO: Computing average Atomic Energies using least squares regression
2023-01-02 18:44:25.442 INFO: Atomic energies: [-233.11162700313903, -799.2398640107622]
2023-01-02 18:44:25.561 INFO: WeightedEnergyForcesLoss(energy_weight=1.000, forces_weight=10.000)
2023-01-02 18:44:25.570 INFO: Average number of neighbors: 18.110
2023-01-02 18:44:25.570 INFO: Selected the following outputs: {'energy': True, 'forces': True, 'virials': False, 'stress': False, 'dipoles': False}
2023-01-02 18:44:25.570 INFO: Building model
2023-01-02 18:44:27.340 INFO: ScaleShiftMACE(
  (node_embedding): LinearNodeEmbeddingBlock(
    (linear): Linear(2x0e -> 17x0e | 34 weights)
  )
  (radial_embedding): RadialEmbeddingBlock(
    (bessel_fn): BesselBasis(r_max=4.0, num_basis=8, trainable=False)
    (cutoff_fn): PolynomialCutoff(p=5.0, r_max=4.0)
  )
  (spherical_harmonics): SphericalHarmonics()
  (atomic_energies_fn): AtomicEnergiesBlock(energies=[-233.1116, -799.2399])
  (interactions): ModuleList(
    (0): RealAgnosticResidualInteractionBlock(
      (linear_up): Linear(17x0e -> 17x0e | 289 weights)
      (conv_tp): TensorProduct(17x0e x 1x0e+1x1o+1x2e+1x3o -> 17x0e+17x1o+17x2e+17x3o | 68 paths | 68 weights)
      (conv_tp_weights): FullyConnectedNet[8, 64, 64, 64, 68]
      (linear): Linear(17x0e+17x1o+17x2e+17x3o -> 17x0e+17x1o+17x2e+17x3o | 1156 weights)
      (skip_tp): FullyConnectedTensorProduct(17x0e x 2x0e -> 17x0e+13x1o | 578 paths | 578 weights)
      (reshape): reshape_irreps()
    )
    (1): RealAgnosticResidualInteractionBlock(
      (linear_up): Linear(17x0e+13x1o -> 17x0e+13x1o | 458 weights)
      (conv_tp): TensorProduct(17x0e+13x1o x 1x0e+1x1o+1x2e+1x3o -> 30x0e+43x1o+43x2e+30x3o | 146 paths | 146 weights)
      (conv_tp_weights): FullyConnectedNet[8, 64, 64, 64, 146]
      (linear): Linear(30x0e+43x1o+43x2e+30x3o -> 17x0e+17x1o+17x2e+17x3o | 2482 weights)
      (skip_tp): FullyConnectedTensorProduct(17x0e+13x1o x 2x0e -> 17x0e | 578 paths | 578 weights)
      (reshape): reshape_irreps()
    )
  )
  (products): ModuleList(
    (0): EquivariantProductBasisBlock(
      (symmetric_contractions): SymmetricContraction(
        (contractions): ModuleDict(
          (17x0e): Contraction(
            (weights): ParameterDict(
                (1): Parameter containing: [torch.DoubleTensor of size 2x1x17]
                (2): Parameter containing: [torch.DoubleTensor of size 2x4x17]
                (3): Parameter containing: [torch.DoubleTensor of size 2x23x17]
            )
          )
          (13x1o): Contraction(
            (weights): ParameterDict(
                (1): Parameter containing: [torch.DoubleTensor of size 2x1x17]
                (2): Parameter containing: [torch.DoubleTensor of size 2x6x17]
                (3): Parameter containing: [torch.DoubleTensor of size 2x51x17]
            )
          )
        )
      )
      (linear): Linear(17x0e+13x1o -> 17x0e+13x1o | 458 weights)
    )
    (1): EquivariantProductBasisBlock(
      (symmetric_contractions): SymmetricContraction(
        (contractions): ModuleDict(
          (17x0e): Contraction(
            (weights): ParameterDict(
                (1): Parameter containing: [torch.DoubleTensor of size 2x1x17]
                (2): Parameter containing: [torch.DoubleTensor of size 2x4x17]
                (3): Parameter containing: [torch.DoubleTensor of size 2x23x17]
            )
          )
        )
      )
      (linear): Linear(17x0e -> 17x0e | 289 weights)
    )
  )
  (readouts): ModuleList(
    (0): LinearReadoutBlock(
      (linear): Linear(17x0e+13x1o -> 1x0e | 17 weights)
    )
    (1): NonLinearReadoutBlock(
      (linear_1): Linear(17x0e -> 16x0e | 272 weights)
      (non_linearity): Activation [x] (16x0e -> 16x0e)
      (linear_2): Linear(16x0e -> 1x0e | 16 weights)
    )
  )
  (scale_shift): ScaleShiftBlock(scale=0.239862, shift=-0.002303)
)
2023-01-02 18:44:27.342 INFO: Number of parameters: 41607
2023-01-02 18:44:27.342 INFO: Optimizer: Adam (
Parameter Group 0
    amsgrad: True
    betas: (0.9, 0.999)
    capturable: False
    eps: 1e-08
    foreach: None
    lr: 0.01
    maximize: False
    name: embedding
    weight_decay: 0.0

Parameter Group 1
    amsgrad: True
    betas: (0.9, 0.999)
    capturable: False
    eps: 1e-08
    foreach: None
    lr: 0.01
    maximize: False
    name: interactions_decay
    weight_decay: 5e-07

Parameter Group 2
    amsgrad: True
    betas: (0.9, 0.999)
    capturable: False
    eps: 1e-08
    foreach: None
    lr: 0.01
    maximize: False
    name: interactions_no_decay
    weight_decay: 0.0

Parameter Group 3
    amsgrad: True
    betas: (0.9, 0.999)
    capturable: False
    eps: 1e-08
    foreach: None
    lr: 0.01
    maximize: False
    name: products
    weight_decay: 5e-07

Parameter Group 4
    amsgrad: True
    betas: (0.9, 0.999)
    capturable: False
    eps: 1e-08
    foreach: None
    lr: 0.01
    maximize: False
    name: readouts
    weight_decay: 0.0
)
2023-01-02 18:44:27.343 INFO: Using gradient clipping with tolerance=10.000
2023-01-02 18:44:27.343 INFO: Started training
Traceback (most recent call last):
  File "/Users/tks32/work/mace/scripts/run_train.py", line 488, in <module>
    main()
  File "/Users/tks32/work/mace/scripts/run_train.py", line 427, in main
    tools.train(
  File "/Users/tks32/work/mace/mace/tools/train.py", line 69, in train
    _, opt_metrics = take_step(
  File "/Users/tks32/work/mace/mace/tools/train.py", line 211, in take_step
    output = model(
  File "/Users/tks32/opt/miniconda3/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/tks32/work/mace/mace/modules/models.py", line 281, in forward
    node_feats = product(
  File "/Users/tks32/opt/miniconda3/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/tks32/work/mace/mace/modules/blocks.py", line 181, in forward
    return self.linear(node_feats) + sc
  File "/Users/tks32/opt/miniconda3/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/tks32/opt/miniconda3/envs/mace/lib/python3.9/site-packages/e3nn/o3/_linear.py", line 276, in forward
    return self._compiled_main(features, weight, bias)
  File "/Users/tks32/opt/miniconda3/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "<eval_with_key>.45", line 8, in forward
    getitem = getattr_1[slice(None, -1, None)];  getattr_1 = None
    add = getitem + (56,);  getitem = None
    reshape = x.reshape(-1, 56);  x = None
              ~~~~~~~~~ <--- HERE
    getattr_2 = reshape.shape
    getitem_1 = getattr_2[0];  getattr_2 = None
RuntimeError: shape '[-1, 56]' is invalid for input of size 21080

```

**Comment by davkovacs** [comment]
This is expected behavior, but I agree that it should fail with a nicer error message. All of the irreps should have the same number of channels.

**Comment by ilyes319** [comment]
This has now an assert here https://github.com/ACEsuit/mace/blob/dfa04a155703af9dd069a52e6ed34d5d589887c6/scripts/run_train.py#L217
