### ISSUE TITLE
AttributeError: 'Irreps' object has no attribute 'lmax' when using cueq

### ISSUE THREAD

**Issue by alinelena** [ACEsuit/mace#732]
When using cueq for descriptors I get the above error.

test is simple

```
from ase.io import read
import numpy as np
from mace.calculators import MACECalculator
calculator = MACECalculator(model_paths="../ft_v2/BiVO_v2.model",enable_cueq=True, device='cuda')
init_conf = read('TS-2x2x2-npt-T300.0-p0.0-traj.extxyz',)
descriptors = calculator.get_descriptors(init_conf)
print(descriptors)
```
from ase.io import read
import numpy as np
from mace.calculators import MACECalculator
calculator = MACECalculator(model_paths="../ft_v2/BiVO_v2.model",enable_cueq=True, device='cuda')
init_conf = read('TS-2x2x2-npt-T300.0-p0.0-traj.extxyz',)
descriptors = calculator.get_descriptors(init_conf)
print(descriptors)

```

full trace

```
Converting models to CuEq for acceleration
/work4/scd/scarf562/micromamba/micromamba/envs/janus-3/lib/python3.11/site-packages/mace/modules/models.py:69: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  "atomic_numbers", torch.tensor(atomic_numbers, dtype=torch.int64)
No dtype selected, switching to float64 to match model dtype.
Traceback (most recent call last):
  File "/work4/scd/scarf562/ml/BiVO4-MLIP/ft/md/./test.py", line 6, in <module>
    descriptors = calculator.get_descriptors(init_conf)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work4/scd/scarf562/micromamba/micromamba/envs/janus-3/lib/python3.11/site-packages/mace/calculators/mace.py", line 410, in get_descriptors
    l_max = irreps_out.lmax
            ^^^^^^^^^^^^^^^
AttributeError: 'Irreps' object has no attribute 'lmax'
```

without cueq things work as expected

**Comment by ilyes319** [comment]
@alinelena Should be fixed in latest main
