### ISSUE TITLE
Error during NPT simulation

### ISSUE THREAD

**Issue by nihil39** [ACEsuit/mace#735]
Hi, 

I have this error (I don't know if this is a bug or not, sorry) while performing a NPT simulation with our MACE trained potential. With NVT and NVE everything works fine and also using MACE-MP0 model with NPT. Maybe I should have set one option while training the model?

Thanks for any help.

Scripts used and error below

Error message:
```
Traceback (most recent call last):
  File "/leonardo_work/IscrC_MLFFSHNC/massimo/MACE/Scripts/ASE_MACE_NPT.py", line 78, in <module>
    dyn.run(number_of_timesteps)
  File "/leonardo/home/userexternal/mciacchi/mace_gpu_venv/lib/python3.10/site-packages/ase/md/npt.py", line 284, in run
    self.step()
  File "/leonardo/home/userexternal/mciacchi/mace_gpu_venv/lib/python3.10/site-packages/ase/md/npt.py", line 354, in step
    force = self.forcecalculator()
  File "/leonardo/home/userexternal/mciacchi/mace_gpu_venv/lib/python3.10/site-packages/ase/md/npt.py", line 362, in forcecalculator
    return self.atoms.get_forces(md=True)
  File "/leonardo/home/userexternal/mciacchi/mace_gpu_venv/lib/python3.10/site-packages/ase/atoms.py", line 812, in get_forces
    forces = self._calc.get_forces(self)
  File "/leonardo/home/userexternal/mciacchi/mace_gpu_venv/lib/python3.10/site-packages/ase/calculators/abc.py", line 30, in get_forces
    return self.get_property('forces', atoms)
  File "/leonardo/home/userexternal/mciacchi/mace_gpu_venv/lib/python3.10/site-packages/ase/calculators/singlepoint.py", line 49, in get_property
    raise PropertyNotImplementedError(
ase.calculators.calculator.PropertyNotImplementedError: The property "forces" is not available.
```

Python script to run the simulation:

```
import time
import os
import sys
from datetime import datetime
start_time = time.time()
start_human_time = datetime.now()
import ase.units as units
from ase.io import read, write
from ase.md import MDLogger
from ase.md.npt import NPT
from ase.io.trajectory import Trajectory
from mace.calculators import MACECalculator
from ase.md.velocitydistribution import MaxwellBoltzmannDistribution, Stationary

model_dir = "model_000"
model_name = "model.model"
base_path = "/leonardo_work/IscrC_MLFFSHNC/massimo/MACE"

model_path = f"{base_path}/{model_dir}"
init_confs_path = f"{base_path}/Init_confs"
results_folder = f"{base_path}/{model_dir}/"

run_name = 'NPT_001'

if os.path.exists(f'{base_path}/{model_dir}/Run_{run_name}'):
# Stop execution and display error message
    raise FileExistsError(f"The directory '{base_path}/{model_dir}/Run_{run_name}' already exists. Choose a different run name or delete the existing directory.")
else:
    # Create directory if it doesn't exist
    os.makedirs(f'{base_path}/{model_dir}/Run_{run_name}', exist_ok=False)
    print(f"Directory '{base_path}/{model_dir}/Run_{run_name}' created successfully.")

conf_file = "every10_ts_NVT_300K_0_972gcc.traj"

init_conf = read(f'{init_confs_path}/{conf_file}', index = '-1')
calculator = MACECalculator(model_paths = f'{model_path}/{model_name}', device = 'cuda', default_dtype = 'float64')

# Attach the calculator to the atoms object

#from ase.parallel import world

number_of_timesteps = 50000
temperature = 300.0
timestep_fs = 0.25
sigma   = 1.01325     # External pressure in bar
ttime   = 20.0    # Time constant in fs
pfactor = 2e6     # Barostat parameter in GPa

#MaxwellBoltzmannDistribution(init_conf, temperature_K = temperature, force_temp = True)
#Stationary(init_conf)

dyn = NPT(init_conf,
        timestep = timestep_fs * units.fs,
        temperature_K = temperature,
        externalstress = sigma * units.bar,
        ttime = ttime * units.fs,
        pfactor = pfactor * units.GPa * (units.fs**2)

        #trajectory = traj_filename,
        #loginterval = num_interval    
      )

#dyn = NPTBerendsen(init_conf, timestep = 1 * units.fs, temperature_K=300, taut=100 * units.fs, pressure_au = 1.01325 * units.bar, taup = 1000 * units.fs, compressibility_au = 4.57e-5 / units.bar)

dyn.attach(MDLogger(dyn, init_conf, f'{base_path}/{model_dir}/Run_{run_name}/md_NPT.log', header = True, stress = True, peratom = True, mode = "w"), interval = 1)

traj = Trajectory(f'{base_path}/{model_dir}/Run_{run_name}/trajectory_NPT.traj', 'w', init_conf)

dyn.attach(traj.write, interval = 1)

def write_frame():
    dyn.atoms.write(f'{base_path}/{model_dir}/Run_{run_name}/trajectory_NPT.xyz', append = True)

dyn.attach(write_frame, interval = 1)

start_dyn_time = time.time()

dyn.run(number_of_timesteps)
```

**Comment by ilyes319** [comment]
does your script work fine witch mp0?

**Comment by ilyes319** [comment]
reading you need to add init_conf.calc = calculator somewhere before running the MD.
