### ISSUE TITLE
--enbale_cueq gives an error when using a finetuned model based on the foundation model MACE-OFF23 medium

### ISSUE THREAD

**Issue by Swiftily** [ACEsuit/mace#738]
**Describe the bug**
I fientune the foundation model MACE-OFF23-medium and use the tag --enbale_cueq to accelerate. Then it gives the following error:
```
Converting models to CuEq for acceleration
Traceback (most recent call last):
  File "/share1/fangwei/3Ala_sol_REMD1/1/mace_driver.py", line 17, in <module>
    mace_calc = MACECalculator(
  File "/share/apps/anaconda3/envs/mace2/lib/python3.10/site-packages/mace/calculators/mace.py", line 139, in __init__
    self.models = [
  File "/share/apps/anaconda3/envs/mace2/lib/python3.10/site-packages/mace/calculators/mace.py", line 140, in <listcomp>
    run_e3nn_to_cueq(model, device=device).to(device)
  File "/share/apps/anaconda3/envs/mace2/lib/python3.10/site-packages/mace/cli/convert_e3nn_cueq.py", line 135, in run
    max_L = config["hidden_irreps"].lmax
KeyError: 'hidden_irreps'
```
**If I use the original foundation model, everything goes well.**
The finetuning script and training log is attached.

**Comment by Swiftily** [comment]
[mace_train.txt](https://github.com/user-attachments/files/18055351/mace_train.txt)
[training.log](https://github.com/user-attachments/files/18055352/training.log)

**Comment by ilyes319** [comment]
What version of MACE are you using? Can you make sure to update to the latest pypi mace version in 0.3.9 and test again.

**Comment by ilyes319** [comment]
Can you post your input here?

**Comment by mwswift-nrl** [comment]
Simplest case is just trying to construct a MACECalculator.  Would info on the training be helpful?

```
Python 3.11.10 (main, Oct  3 2024, 07:29:13) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mace, torch
>>> from mace.calculators import MACECalculator
/home/cluster/swift/.local/lib/python3.11/site-packages/e3nn/o3/_wigner.py:10: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  _Jd, _W3j_flat, _W3j_indices = torch.load(os.path.join(os.path.dirname(__file__), 'constants.pt'))
>>> 
>>> print(mace.__version__)
0.3.9
>>> print(torch.__version__)
2.5.1+cu124
>>> 
>>> MACECalculator(model_paths="../MACE_DMAMBS_DMABS_2024_12_06.model", device='cuda', enable_cueq = True)       
/home/cluster/swift/.local/lib/python3.11/site-packages/mace/calculators/mace.py:135: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  torch.load(f=model_path, map_location=device)
/home/cluster/swift/.local/lib/python3.11/site-packages/torch/serialization.py:1328: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
  warnings.warn(
Converting models to CuEq for acceleration
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cluster/swift/.local/lib/python3.11/site-packages/mace/calculators/mace.py", line 140, in __init__
    self.models = [
                  ^
  File "/home/cluster/swift/.local/lib/python3.11/site-packages/mace/calculators/mace.py", line 141, in <listcomp>
    run_e3nn_to_cueq(model, device=device).to(device)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cluster/swift/.local/lib/python3.11/site-packages/mace/cli/convert_e3nn_cueq.py", line 135, in run
    max_L = config["hidden_irreps"].lmax
            ~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'hidden_irreps'
```

**Comment by ilyes319** [comment]
can you share your model with me at ib467@cam.ac.uk so I can reproduce that?

**Comment by ilyes319** [comment]
@mwswift-nrl thank you! Looking into it.

**Comment by ilyes319** [comment]
Looking into it, it seems that you must be using the jit compiled model to create your calculator. Can you please try the saved model that has "run" inside it, it should be located in your checkpoint folder.

**Comment by ilyes319** [comment]
@Swiftily Make sure to try the same thing please, you are probably using a jit compiled model.

**Comment by mwswift-nrl** [comment]
Indeed I was able to create a Calculator using the other saved model. Thanks!

**Comment by ilyes319** [comment]
Welcome closing now, switching to a discussion to help @Swiftily .
