### ISSUE TITLE
Problem in computing body order energy contributions when evaluating a test set

### ISSUE THREAD

**Issue by nihil39** [ACEsuit/mace#751]
Hi, 

when I try to run the following command in order to evaluate my test set

`mace_eval_configs --model ${MODEL_NAME} --configs ${DATASET_PATH}/${FILE_NAME} --output ${DATASET_PATH}/${FILE_NAME_A}_eval_${MODEL_FOLDER}_cuda.xyz --device cuda --compute_stress --default_dtype float64 --batch_size 5 --return_contributions`

 I get the following error 

```
Traceback (most recent call last):
  File "/leonardo/home/userexternal/mciacchi/mace_gpu_venv/bin/mace_eval_configs", line 8, in <module>
    sys.exit(main())
  File "/leonardo/home/userexternal/mciacchi/mace_gpu_venv/lib/python3.10/site-packages/mace/cli/eval_configs.py", line 70, in main
    run(args)
  File "/leonardo/home/userexternal/mciacchi/mace_gpu_venv/lib/python3.10/site-packages/mace/cli/eval_configs.py", line 126, in run
    contributions_list.append(torch_tools.to_numpy(output["contributions"]))
KeyError: 'contributions'
```
if I don't set the `--return_contributions` flag, everything works. 

I think it's a bug but maybe I'm wrong. 

Thank you for any help.

**Comment by nihil39** [comment]
> return_contributions is not supported for the ScaleShiftMACE models. I think I ll just remove this anyway, it made more sense at the botnet time, but with MACE, the body order are already summed at each layer, such that you can not really analyse the full expansion this way.

Ok, thanks. I was in fact trying to evaluate a MACE model, not a ScaleShiftMACE one.
