### ISSUE TITLE
RuntimeError: expected scalar type Double but found Float

### ISSUE THREAD

**Issue by kkly1995** [ACEsuit/mace#84]
I recently updated my local copy of MACE, pulled yesterday (Feb. 20) and ran into the following problem when calling an evaluation with ASE:
```
Traceback (most recent call last):
  File "/home/ly1/MCASE/bin/mcase_table_half", line 66, in <module>
    energy = walker.get_potential_energy()
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/ase/atoms.py", line 731, in get_potential_energy
    energy = self._calc.get_potential_energy(self)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/ase/calculators/calculator.py", line 709, in get_potential_energy
    energy = self.get_property('energy', atoms)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/ase/calculators/calculator.py", line 737, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/mace/calculators/mace.py", line 71, in calculate
    out = self.model(batch.to_dict(), compute_stress=True)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/mace/modules/models.py", line 295, in forward
    node_e0 = self.atomic_energies_fn(data["node_attrs"])
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ly1/.conda/envs/mace/lib/python3.9/site-packages/mace/modules/blocks.py", line 137, in forward
    return torch.matmul(x, self.atomic_energies)
RuntimeError: expected scalar type Double but found Float
```

I have verified that training works with this version, as I trained a new model overnight, and I actually tried using that new model above. Below is the training script:
```
$ cat input.sh
python /home/ly1/mace/scripts/run_train.py \
	--name="hydrogen" \
	--train_file="/home/ly1/H/metallic/subtracted_data/qmc/training.xyz" \
	--valid_fraction=0.05 \
	--test_file="/home/ly1/H/metallic/subtracted_data/qmc/testing.xyz" \
	--config_type_weights='{"Default":1.0}' \
	--E0s="average" \
	--model="MACE" \
	--hidden_irreps='64x0e + 64x1o' \
	--r_max=3.0 \
	--default_dtype='float32' \
	--batch_size=3 \
	--valid_batch_size=3 \
	--max_num_epochs=500 \
	--ema \
	--ema_decay=0.99 \
	--amsgrad \
	--restart_latest \
	--device=cuda
```

**Comment by davkovacs** [comment]
Hi! Thanks for submitting an issue. 

Can you send us the code you used to create the calculator? 
One source of the problem might be that you used float32 for training, and the default dtype for the calculator is float64.  Have you specified the data type to float32 when creating the calculator by setting the keyword ` default_dtype="float32"` ?

**Comment by kkly1995** [comment]
That specification worked, thanks for the quick response. The previous version of MACE worked without it, which is why I hadn't considered it here.
